### ISSUE TITLE
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by karai17** [JoelBesada/activate-power-mode#1]
This happens when I try to type or delete text after activating via ctrl+alt+o.

```
C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:770

TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at TypeError (native)
    at Object.module.exports.ActivatePowerMode.spawnParticles (file:///C:/Users/lmann/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:84:13)
    at Object.debounced [as throttledSpawnParticles] (C:\Users\lmann\.atom\packages\activate-power-mode\node_modules\lodash.throttle\node_modules\lodash.debounce\index.js:182:23)
    at Object.module.exports.ActivatePowerMode.onChange (file:///C:/Users/lmann/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:58:6)
    at Emitter.module.exports.Emitter.emit (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:645:20)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:550:12)
    at TextBuffer.module.exports.TextBuffer.delete (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:652:19)
    at Selection.module.exports.Selection.deleteSelectedText (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\selection.js:600:37)
    at Selection.module.exports.Selection.delete (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\selection.js:557:19)
    at C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\text-editor.js:749:35
    at C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\text-editor.js:771:29
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:765:18)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\text-editor.js:1152:26)
    at C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\text-editor.js:765:24
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\text-editor.js:2013:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\text-editor.js:1979:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\text-editor.js:763:19)
    at TextEditor.module.exports.TextEditor.delete (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\text-editor.js:748:19)
    at TextEditor.commandRegistry.add.stopEventPropagationAndGroupUndo.core:delete (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\register-default-commands.js:344:30)
    at C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\register-default-commands.js:573:34
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:765:18)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\text-editor.js:1152:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\register-default-commands.js:572:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (C:\Users\lmann\AppData\Local\atom\app-1.2.4\resources\app.asar\src\window-event-handler.js:3:61)
```

**Comment by raulsntos** [comment]
I had this issue in version 0.3.1 but it's gone now in 0.3.2

**Comment by karai17** [comment]
Yeah, this seems to be fixed now. :D
