### ISSUE TITLE
with Atom1.6.2: Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by moonfoam** [JoelBesada/activate-power-mode#115]
Not work,only show the following msg:
Uncaught TypeError: Cannot read property 'querySelector' of null
/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:816
Hide Stack Trace
TypeError: Cannot read property 'querySelector' of null
    at Object.module.exports.ActivatePowerMode.calculateCursorOffset (/home/wangchi/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:52:47)
    at Object.module.exports.ActivatePowerMode.spawnParticles (/home/wangchi/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:91:21)
    at Object.debounced [as throttledSpawnParticles] (/home/wangchi/.atom/packages/activate-power-mode/node_modules/lodash.throttle/node_modules/lodash.debounce/index.js:182:23)
    at Object.module.exports.ActivatePowerMode.onChange (/home/wangchi/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:67:8)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:677:27)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:575:12)
    at Selection.module.exports.Selection.insertText (/usr/share/atom/resources/app.asar/src/selection.js:482:43)
    at /usr/share/atom/resources/app.asar/src/text-editor.js:804:29
    at /usr/share/atom/resources/app.asar/src/text-editor.js:843:29
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:811:18)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1243:26)
    at /usr/share/atom/resources/app.asar/src/text-editor.js:837:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:2123:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:2085:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/share/atom/resources/app.asar/src/text-editor.js:835:19)
    at TextEditor.module.exports.TextEditor.insertText (/usr/share/atom/resources/app.asar/src/text-editor.js:801:19)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/usr/share/atom/resources/app.asar/src/text-editor-component.js:473:35)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/src/text-editor-component.js:3:61)

**Comment by moonfoam** [comment]
I reinstall the Atom and it works fine now :)
