### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash.random'

### ISSUE THREAD

**Issue by Darrry** [JoelBesada/activate-power-mode#117]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.3
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.4.1

### Stack Trace

Uncaught Error: Cannot find module 'lodash.random'

```
At module.js:338

Error: Cannot find module 'lodash.random'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/dary/.atom/packages/activate-power-mode-0.4.1/lib/activate-power-mode.coffee:2:10)
    at Object.<anonymous> (/Users/dary/.atom/packages/activate-power-mode-0.4.1/lib/activate-power-mode.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:220:12)
    at PackageManager.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:55:14)
    at PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:658:63)
    at PackageCard.module.exports.PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:611:34)
    at PackageCard.module.exports.PackageCard.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:205:17)
    at PackageCard.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new PackageCard (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:22:48)
    at InstallPanel.module.exports.InstallPanel.addPackageViews (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:280:41)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:341:28
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/atom-io-client.js:62:20
    at AtomIoClient.module.exports.AtomIoClient.fetchFromCache (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/atom-io-client.js:153:16)
    at AtomIoClient.module.exports.AtomIoClient.featuredPackages (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/atom-io-client.js:59:19)
    at InstallPanel.module.exports.InstallPanel.loadFeaturedPackages (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:334:28)
    at InstallPanel.module.exports.InstallPanel.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:145:19)
    at InstallPanel.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at InstallPanel.ScrollView [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new InstallPanel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/install-panel.js:30:49)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:159:18
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:274:19)
    at SettingsView.module.exports.SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:320:24)
    at HTMLAnchorElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:123:24)
    at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:02.8.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:02.5.0 editor:toggle-line-comments (div.panels-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
keymaps, vundefined
lib, vundefined
menus, vundefined
styles, vundefined

# Dev
No dev packages
```

**Comment by lexcast** [comment]
try installing activate-power-mode package again

**Comment by lexcast** [comment]
@Darrry try installing with apm running: `apm install activate-power-mode`
