### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by ambitionkingman** [JoelBesada/activate-power-mode#119]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Unknown Windows Version
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'querySelector' of null

```
At C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:816

TypeError: Cannot read property 'querySelector' of null
    at Object.module.exports.ActivatePowerMode.calculateCursorOffset (file:///C:/Users/wuwei01/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:52:47)
    at Object.module.exports.ActivatePowerMode.spawnParticles (file:///C:/Users/wuwei01/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:91:21)
    at Object.debounced [as throttledSpawnParticles] (C:\Users\wuwei01\.atom\packages\activate-power-mode\node_modules\lodash.throttle\node_modules\lodash.debounce\index.js:182:23)
    at Object.module.exports.ActivatePowerMode.onChange (file:///C:/Users/wuwei01/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:67:8)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:677:27)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:575:12)
    at Selection.module.exports.Selection.insertText (C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\src\selection.js:482:43)
    at C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\src\text-editor.js:804:29
    at C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\src\text-editor.js:843:29
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:811:18)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\src\text-editor.js:1243:26)
    at C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\src\text-editor.js:837:24
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\src\text-editor.js:2123:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\src\text-editor.js:2085:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\src\text-editor.js:835:19)
    at TextEditor.module.exports.TextEditor.insertText (C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\src\text-editor.js:801:19)
    at TextEditor.object.(anonymous function) [as insertText] (C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\src\text-editor-component.js:473:35)
    at HTMLDivElement.<anonymous> (C:\Users\wuwei01\AppData\Local\atom\app-1.6.2\resources\app.asar\src\text-editor-component.js:3:61)
```

### Commands

```
 30x -9:11.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -7:23.5.0 window:decrease-font-size (atom-text-editor.editor.power-mode.is-focused)
  2x -4:56.8.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.tinted-tab-bar.compact-tab-bar.panel-shadows.panel-contrast.use-animations.compact-tree-view.blend-tree-view.theme-atom-dark-syntax.theme-atom-material-ui)
     -4:54.1.0 go-to-line:toggle (atom-text-editor.editor.power-mode)
     -4:48.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -4:40.7.0 window:decrease-font-size (a.inline-block)
  7x -4:39.4.0 window:increase-font-size (a.inline-block)
  6x -4:36.4.0 window:decrease-font-size (a.inline-block)
  6x -2:44.2.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -0:30.5.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.tinted-tab-bar.compact-tab-bar.panel-shadows.panel-contrast.use-animations.compact-tree-view.blend-tree-view.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:16.7.0 pane:reopen-closed-item (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "activate-power-mode": {
    "particles": {
      "size": {},
      "spawnCount": {},
      "totalCount": {}
    },
    "screenShake": {}
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.4.1
autocomplete-java, v1.2.1
build-coffeescript, v0.1.0
java-class-complete, v0.0.6
language-oracle, v1.4.1
linter, v1.11.4
linter-javac, v1.8.1
Sublime-Style-Column-Selection, v1.5.1
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by nathanchapman** [comment]
Please uninstall and reinstall Atom and report back. Another user was experiencing this issue and that solved it for them.

**Comment by kokhoor** [comment]
Same problem, but on Mac. Uninstalled and reinstalled same issue:

Atom version 1.7.2
activate-power-mode 0.4.1

/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:833
Hide Stack Trace
TypeError: Cannot read property 'querySelector' of null
    at Object.module.exports.ActivatePowerMode.calculateCursorOffset (/Users/kokhoor/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:52:47)
    at Object.module.exports.ActivatePowerMode.spawnParticles (/Users/kokhoor/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:91:21)
    at Object.debounced [as throttledSpawnParticles] (/Users/kokhoor/.atom/packages/activate-power-mode/node_modules/lodash.throttle/node_modules/lodash.debounce/index.js:182:23)
    at Object.module.exports.ActivatePowerMode.onChange (/Users/kokhoor/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:67:8)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:692:27)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:602:12)
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:483:43)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:835:29
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:874:29
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1274:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:868:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2166:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2132:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:866:19)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:832:19)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:474:35)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

**Comment by foreshadow** [comment]
Try enabling shadow BOM

**Comment by kokhoor** [comment]
In Settings, there is no shadow BOM option.

![image](https://cloud.githubusercontent.com/assets/2721145/14972722/9f60ea1a-1111-11e6-8d1b-2890542d07fd.png)
![image](https://cloud.githubusercontent.com/assets/2721145/14972724/ac02d558-1111-11e6-8060-fbbd08e0aeae.png)

**Comment by ansi6622** [comment]
same ^

**Comment by foreshadow** [comment]
Maybe it is in **Editor** settings.

**Comment by motss** [comment]
Really need to state that Shadow DOM is required to make this worked.

**Comment by kokhoor** [comment]
Fixed for me. Shadow DOM is in Editor Settings, scroll all the way to the bottom to find it. May need to restart Atom for this to take effect.

![image](https://cloud.githubusercontent.com/assets/2721145/15014026/ecca0d02-1235-11e6-920b-c211eaaab3e4.png)

**Comment by lexcast** [comment]
We should mention that requirement in the readme

**Comment by lexcast** [comment]
shadow dom issues are fixed already

**Comment by motss** [comment]
@lexcast Does it mean Shadow DOM is not strictly required?

**Comment by lexcast** [comment]
@motss Yes, see #97
