### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by qddegtya** [JoelBesada/activate-power-mode#12]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.3.2

### Stack Trace

Uncaught TypeError: Cannot read property 'querySelector' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:770

TypeError: Cannot read property 'querySelector' of null
    at Object.module.exports.ActivatePowerMode.calculateCursorOffset (/Users/archer/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:35:47)
    at Object.module.exports.ActivatePowerMode.spawnParticles (/Users/archer/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:65:21)
    at Object.debounced [as throttledSpawnParticles] (/Users/archer/.atom/packages/activate-power-mode/node_modules/lodash.throttle/node_modules/lodash.debounce/index.js:182:23)
    at Object.module.exports.ActivatePowerMode.onChange (/Users/archer/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:48:6)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:645:20)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:550:12)
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:482:43)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:732:29
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:771:29
```

### Commands

```
     -0:25.8.0 application:open (input.hidden-input)
     -0:09.6.0 vim-mode:activate-insert-mode (input.hidden-input)
     -0:09.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:09.0 editor:newline (input.hidden-input)
     -0:08.8.0 core:move-up (input.hidden-input)
     -0:06.5.0 activate-power-mode:toggle (input.hidden-input)
  3x -0:04.4.0 core:backspace (input.hidden-input)
     -0:00.4.0 activate-power-mode:toggle (input.hidden-input)
     -0:00.0 core:backspace (input.hidden-input)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.3.2
color-picker, v2.0.13
emmet, v2.3.15
javascript-snippets, v1.0.0
language-vue-component, v0.3.0
linter, v1.11.2
linter-eslint, v5.2.4
minimap, v4.16.2
travis-ci-status, v0.18.0
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by qddegtya** [comment]
I got it.......because this line: scrollViewRect = @editorElement.shadowRoot.querySelector(".scroll-view").getBoundingClientRect()

I open the CONFIG -> Use Shadow DOM

Then fix it~
