### ISSUE TITLE
Uncaught TypeError: Cannot read property 'uploadFile' of undefined

### ISSUE THREAD

**Issue by wordhardqi** [JoelBesada/activate-power-mode#120]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Unknown Windows Version
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'uploadFile' of undefined

```
At /C:/Users/Qi/.atom/packages/remote-sync/index.coffee:80

TypeError: Cannot read property 'uploadFile' of undefined
    at handleEvent (file:///C:/Users/Qi/.atom/packages/remote-sync/index.coffee:42:3)
    at atom-workspace.disposables.add.atom.commands.add.remote-sync:upload-file (file:///C:/Users/Qi/.atom/packages/remote-sync/index.coffee:85:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Qi\AppData\Local\atom\app-1.6.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Qi\AppData\Local\atom\app-1.6.2\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Qi\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Qi\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\Qi\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Qi\AppData\Local\atom\app-1.6.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Qi\AppData\Local\atom\app-1.6.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Qi\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Qi\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\Qi\AppData\Local\atom\app-1.6.2\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\Qi\AppData\Local\atom\app-1.6.2\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -1:25.5.0 intentions:highlight (atom-text-editor.editor.is-focused)
     -1:25.5.0 core:paste (atom-text-editor.editor.is-focused)
     -1:17.5.0 intentions:highlight (atom-text-editor.editor.is-focused)
     -1:17.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:43.7.0 intentions:highlight (atom-text-editor.editor.is-focused)
     -0:43.3.0 window:run-package-specs (atom-text-editor.editor.is-focused)
     -0:42.5.0 intentions:highlight (atom-text-editor.editor.is-focused)
     -0:42.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:22.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:21.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:21.3.0 remote-sync:upload-folder (atom-text-editor.editor)
     -0:12.1.0 intentions:highlight (atom-text-editor.editor.is-focused)
     -0:12 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:08.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:04.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.4.0 remote-sync:upload-file (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "Ensime",
      "Ensime",
      "Ensime",
      "Ensime",
      "Ensime",
      "Ensime",
      "Ensime",
      "Ensime",
      "Ensime",
      "vim-mode"
    ],
    "themes": [
      "two-light-ui",
      "one-light-syntax"
    ]
  },
  "activate-power-mode": {
    "particles": {
      "size": {},
      "spawnCount": {},
      "totalCount": {}
    },
    "screenShake": {
      "maxIntensity": 2
    }
  }
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.54
hyperclick, v0.0.35
intentions, v1.0.5
language-scala, v1.1.6
linter, v1.11.4
linter-scalac, v1.4.0
remote-sync, v3.5.0
two-light-ui, v1.0.0

# Dev
No dev packages
```

**Comment by lexcast** [comment]
It seems that this error is caused by the remote-sync package. I don't know why atom shows the activate-power-mode instead.

**Comment by wordhardqi** [comment]
Thanks. I also noticed this. Very
 excited to hear from you



Sent from my Mi phoneOn Daniel Alejandro Cast <notifications@github.com>, Apr 21, 2016 6:34 AM wrote:It seems that this error is caused by the remote-sync package. I don't know why atom shows the activate-power-mode instead.
