### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by blade254353074** [JoelBesada/activate-power-mode#13]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.3.2
### Stack Trace

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

```
At /C:/Users/Administrator/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:44

TypeError: Cannot read property 'getBoundingClientRect' of null
    at Object.module.exports.ActivatePowerMode.calculateCursorOffset (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:35:77)
    at Object.module.exports.ActivatePowerMode.spawnParticles (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:65:21)
    at Object.debounced [as throttledSpawnParticles] (C:\Users\Administrator\.atom\packages\activate-power-mode\node_modules\lodash.throttle\node_modules\lodash.debounce\index.js:182:23)
    at Object.module.exports.ActivatePowerMode.onChange (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:48:6)
    at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:645:20)
    at TextBuffer.module.exports.TextBuffer.undo (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:732:16)
    at C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\src\text-editor.js:1136:31
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\src\text-editor.js:2017:18)
    at TextEditor.module.exports.TextEditor.avoidMergingSelections (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\src\text-editor.js:1999:35)
    at TextEditor.module.exports.TextEditor.undo (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\src\text-editor.js:1134:12)
    at TextEditor.commandRegistry.add.stopEventPropagation.core:undo (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\src\register-default-commands.js:223:21)
    at atom-text-editor.newCommandListeners.(anonymous function) (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\src\register-default-commands.js:554:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\src\window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
     -4:48.7.0 application:new-file (atom-text-editor.editor.is-focused)
     -4:47.3.0 core:paste (atom-text-editor.editor.is-focused)
     -4:45.7.0 fuzzy-finder:toggle-git-status-finder (atom-text-editor.editor.is-focused)
     -4:44.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:44.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:44.1.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -4:41 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -4:41 core:cancel (atom-text-editor.editor.is-focused)
     -4:39 grammar-selector:show (atom-text-editor.editor)
     -4:34.6.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
  8x -4:20.5.0 core:undo (atom-text-editor.editor.is-focused)
     -4:09.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:08.1.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -4:06.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:23.8.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
  4x -0:20.2.0 core:undo (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "typewriter-sounds"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.3.2
atom-beautify, v0.28.19
atom-handlebars, v1.2.0
color-picker, v2.0.13
emmet, v2.3.15
git-plus, v5.6.6
jQuery, v1.2.0
jquery-snippets, v11.0.0
keyboard-sounds, v0.2.0
minimap, v4.16.2
pigments, v0.19.1

# Dev
No dev packages
```

**Comment by lexcast** [comment]
is this still happening with the latest version?

**Comment by lexcast** [comment]
Closing issues on old versions of this package.

Open again if the problem persists with the latest release.

**Comment by Getron** [comment]
The problem still there, in the newest version to.

**Comment by lexcast** [comment]
@Getron can I see your stack trace?

**Comment by lexcast** [comment]
no more information given
