### ISSUE TITLE
Failed to activate the activate-power-mode package

### ISSUE THREAD

**Issue by zhoujiuan** [JoelBesada/activate-power-mode#132]
Error: Cannot find module 'lodash.throttle'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\zja\AppData\Local\atom\app-1.7.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\zja\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/zja/.atom/packages/activate-power-mode-master/lib/activate-power-mode.coffee:1:12)
    at Object.<anonymous> (file:///C:/Users/zja/.atom/packages/activate-power-mode-master/lib/activate-power-mode.coffee:1:1)
    at Module._compile (C:\Users\zja\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\zja\AppData\Local\atom\app-1.7.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\zja\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\zja\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateNow (C:\Users\zja\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:173:16)
    at C:\Users\zja\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\zja\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\zja\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\zja\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:241:20)
    at C:\Users\zja\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\zja\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\zja\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\zja\AppData\Local\atom\app-1.7.2\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\z

**Comment by zhoujiuan** [comment]
what can I do  this

**Comment by lexcast** [comment]
how are you installing the package?

**Comment by ganhb** [comment]
My mistake is：
 Cannot read property 'parentNode' of undefined
what can i do this
help~sososososososos

**Comment by CharlieTLe** [comment]
Are you activating the command while you're in the settings menu? Try activating it while you're editing a file.

**Comment by ganhb** [comment]
thankyou  :)  I reactivated on OK,just ctrl+shift+r

2016-04-26 

甘煌斌 



发件人：Charlie Le <notifications@github.com>
发送时间：2016-04-26 08:31
主题：Re: [JoelBesada/activate-power-mode] Failed to activate the activate-power-mode package (#132)
收件人："JoelBesada/activate-power-mode"<activate-power-mode@noreply.github.com>
抄送："ganhb"<ghblink@163.com>,"Comment"<comment@noreply.github.com>

Are you activating the command while you're in the settings menu? Try activating it while you're editing a file.

**Comment by jabocg** [comment]
I get this error when trying to activate Power Mode without a file open.

**Comment by tonywmnix** [comment]
Updated and got this:

**Atom Version**: 1.8.0-beta3
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.5.0


### Stack Trace

Failed to activate the activate-power-mode package

```
At Cannot read property 'parentNode' of undefined

TypeError: Cannot read property 'parentNode' of undefined
    at Object.module.exports.ActivatePowerMode.setupCanvas (file:///C:/Users/awmoore/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:49:16)
    at Object.module.exports.ActivatePowerMode.activate (file:///C:/Users/awmoore/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:23:9)
    at Package.module.exports.Package.activateNow (C:\Users\awmoore\AppData\Local\atom\app-1.8.0-beta3\resources\app.asar\src\package.js:183:20)
    at C:\Users\awmoore\AppData\Local\atom\app-1.8.0-beta3\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\awmoore\AppData\Local\atom\app-1.8.0-beta3\resources\app.asar\src\package.js:92:15)
    at C:\Users\awmoore\AppData\Local\atom\app-1.8.0-beta3\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\awmoore\AppData\Local\atom\app-1.8.0-beta3\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\awmoore\AppData\Local\atom\app-1.8.0-beta3\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\awmoore\AppData\Local\atom\app-1.8.0-beta3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:389:60
    at exit (C:\Users\awmoore\AppData\Local\atom\app-1.8.0-beta3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\awmoore\AppData\Local\atom\app-1.8.0-beta3\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\awmoore\AppData\Local\atom\app-1.8.0-beta3\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "node-resolver"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.0
atom-typescript, v8.9.1
atom-vim-colon-command-on-command-pallete, v0.2.0
atomic-chrome, v0.3.0
autocomplete-awk, v0.1.2
autocomplete-json, v1.9.1
autocomplete-modules, v1.4.1
autocomplete-python, v1.7.2
autocomplete-xml, v0.8.3
browser-plus, v0.0.60
build-npm-apm, v0.12.0
coffee-compile, v0.21.1
file-icons, v1.7.8
git-hide, v0.1.2
icon-fonts, v2.5.0
javascript-snippets, v1.2.1
language-mscgen, v1.3.0
linter, v1.11.4
linter-shellcheck, v1.2.0
minimap, v4.23.2
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.0
minimap-linter, v1.1.1
mscgen-preview, v1.3.6
node-debugger, vundefined
nodejs-snippets, v2.0.0
package-sync, v1.1.0
pigments, v0.26.0
remote-atom, v1.3.9
svg-preview, v0.7.4
symbol-gen, v1.3.0
tree-view-git-status, v0.2.3
vim-mode, v0.65.0
vim-mode-visual-block, v0.2.15
vim-modeline, v0.4.0
web-view, v3.0.0

# Dev
No dev packages
```

**Comment by lexcast** [comment]
Closing this as the main problem was trying to activate the package without installing dependencies.
@zhoujiuan try installing via apm running: `apm install activate-power-mode`
