### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by MatrixV01** [JoelBesada/activate-power-mode#141]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'appendChild' of null

```
At /Users/BradFincher/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:45

TypeError: Cannot read property 'appendChild' of null
    at Object.module.exports.ActivatePowerMode.subscribeToActiveTextEditor (/Users/BradFincher/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:45:19)
    at /Users/BradFincher/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:19:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:431:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:628:19)
```

### Commands

```
     -3:51.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-icons.theme-seti-syntax.theme-seti-ui.seti-theme-blue)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "file-icons"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.1
atom-html-preview, v0.1.19
atom-ternjs, v0.14.1
color-picker, v2.1.1
highlight-selected, v0.11.2
linter, v1.11.4
linter-jshint, v2.1.0
minimap, v4.23.2
pigments, v0.26.0
react, v0.15.0
seti-syntax, v1.0.1
seti-ui, v1.0.4

# Dev
No dev packages
```

**Comment by lexcast** [comment]
this happens when just updated the package? try reloading atom

**Comment by lexcast** [comment]
Closing issues on old versions of this package.

Open again if the problem persists with the latest release.

**Comment by cemsbr** [comment]
Just happened. Version 1.1.0.

**Comment by shinsters** [comment]
This has started happening for me.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Pro
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v1.0.2


### Stack Trace

Uncaught TypeError: Cannot read property 'appendChild' of null

```
At /C:/Users/john/.atom/packages/activate-power-mode/lib/combo-mode.coffee:76

TypeError: Cannot read property 'appendChild' of null
    at Object.module.exports.setup (file:///C:/Users/john/.atom/packages/activate-power-mode/lib/combo-mode.coffee:50:77)
    at file:///C:/Users/john/.atom/packages/activate-power-mode/lib/power-editor.coffee:23:20
    at Config.module.exports.Config.observeKeyPath (C:\Users\john\AppData\Local\atom\app-1.11.2\resources\app.asar\src\config.js:616:7)
    at Config.module.exports.Config.observe (C:\Users\john\AppData\Local\atom\app-1.11.2\resources\app.asar\src\config.js:141:21)
    at Object.module.exports.enable (file:///C:/Users/john/.atom/packages/activate-power-mode/lib/power-editor.coffee:20:49)
    at Object.module.exports.ActivatePowerMode.enable (file:///C:/Users/john/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:36:18)
    at Object.module.exports.ActivatePowerMode.toggle (file:///C:/Users/john/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:32:38)
    at atom-workspace.subscriptions.add.atom.commands.add.activate-power-mode:toggle (file:///C:/Users/john/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:16:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\john\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\john\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\john\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\john\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\john\AppData\Local\atom\app-1.11.2\resources\app.asar\src\window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (C:\Users\john\AppData\Local\atom\app-1.11.2\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -1:54 tree-view:reveal-active-file (atom-text-editor.editor.is-focused)
     -0:59.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:53.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:06.9.0 activate-power-mode:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "css-color-underline"
    ],
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.0.2 (active)
angularjs, v0.3.5 (active)
atom-beautify, v0.29.13 (active)
autocomplete-angular-material, v0.4.0 (active)
color-picker, v2.2.2 (active)
color-tabs, v0.1.8 (active)
css-color-underline, v1.0.1 (inactive)
css-comb, v2.5.0 (active)
file-icons, v1.7.22 (active)
git-history, v3.2.0 (inactive)
webbox-color, v0.5.9 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (active)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (active)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by shinsters** [comment]
This has started happening for me.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Pro
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v1.0.2


### Stack Trace

Uncaught TypeError: Cannot read property 'appendChild' of null

```
At /C:/Users/john/.atom/packages/activate-power-mode/lib/combo-mode.coffee:76

TypeError: Cannot read property 'appendChild' of null
    at Object.module.exports.setup (file:///C:/Users/john/.atom/packages/activate-power-mode/lib/combo-mode.coffee:50:77)
    at file:///C:/Users/john/.atom/packages/activate-power-mode/lib/power-editor.coffee:23:20
    at Config.module.exports.Config.observeKeyPath (C:\Users\john\AppData\Local\atom\app-1.11.2\resources\app.asar\src\config.js:616:7)
    at Config.module.exports.Config.observe (C:\Users\john\AppData\Local\atom\app-1.11.2\resources\app.asar\src\config.js:141:21)
    at Object.module.exports.enable (file:///C:/Users/john/.atom/packages/activate-power-mode/lib/power-editor.coffee:20:49)
    at Object.module.exports.ActivatePowerMode.enable (file:///C:/Users/john/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:36:18)
    at Object.module.exports.ActivatePowerMode.toggle (file:///C:/Users/john/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:32:38)
    at atom-workspace.subscriptions.add.atom.commands.add.activate-power-mode:toggle (file:///C:/Users/john/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:16:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\john\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\john\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\john\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\john\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\john\AppData\Local\atom\app-1.11.2\resources\app.asar\src\window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (C:\Users\john\AppData\Local\atom\app-1.11.2\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -1:54 tree-view:reveal-active-file (atom-text-editor.editor.is-focused)
     -0:59.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:53.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:06.9.0 activate-power-mode:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "css-color-underline"
    ],
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.0.2 (active)
angularjs, v0.3.5 (active)
atom-beautify, v0.29.13 (active)
autocomplete-angular-material, v0.4.0 (active)
color-picker, v2.2.2 (active)
color-tabs, v0.1.8 (active)
css-color-underline, v1.0.1 (inactive)
css-comb, v2.5.0 (active)
file-icons, v1.7.22 (active)
git-history, v3.2.0 (inactive)
webbox-color, v0.5.9 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (active)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (active)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Cameri** [comment]
Reloading Atom fixed it for me.

**Comment by chenasraf** [comment]
Well this and #280 both happen to me, reloading fixed nothing :(

**Comment by lexcast** [comment]
Hi @chenasraf, how can you reproduce this issue?

**Comment by sidpagariya** [comment]
@lexcast, I removed the package, cleaned all my atom cache, and installed atom again. Then, I installed the package and I got the same issue...
Thanks!

**Comment by sidpagariya** [comment]
I have a package backup facility so I restored all my packages again.
Here's my info:
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package 2.0.0


### Stack Trace

Uncaught TypeError: Cannot read property 'appendChild' of null

```
At /Users/Siddhant/.atom/packages/activate-power-mode/lib/canvas-renderer.coffee:52

TypeError: Cannot read property 'appendChild' of null
    at Object.setupCanvas (/packages/activate-power-mode/lib/canvas-renderer.coffee:52:20)
    at Object.onChangePane (/packages/activate-power-mode/lib/plugin/power-canvas.coffee:15:13)
    at /packages/activate-power-mode/lib/plugin-manager.coffee:88:32
    at Object.onEnabled (/packages/activate-power-mode/lib/plugin-registry.coffee:64:19)
    at Object.runOnChangePane (/packages/activate-power-mode/lib/plugin-manager.coffee:87:21)
    at Object.setupPane (/packages/activate-power-mode/lib/power-editor.coffee:40:20)
    at /packages/activate-power-mode/lib/power-editor.coffee:9:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom-Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom-Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom-Beta.app/Contents/Resources/app/src/workspace.js:551:30
```

### Commands

```
     -2:49.1.0 command-palette:toggle (input.hidden-input)
     -2:42.9.0 core:select-all (input.hidden-input)
  4x -2:42.8.0 core:backspace (input.hidden-input)
     -2:38.8.0 core:select-all (input.hidden-input)
     -2:37.9.0 core:backspace (input.hidden-input)
     -2:36.9.0 editor:consolidate-selections (input.hidden-input)
     -2:36.9.0 core:cancel (input.hidden-input)
     -2:36.3.0 settings-view:open (input.hidden-input)
     -2:22.2.0 command-palette:toggle (input.hidden-input)
     -2:20.1.0 core:confirm (input.hidden-input)
     -2:20.1.0 config-import-export:export (input.hidden-input)
     -2:17.3.0 core:confirm (input.hidden-input)
     -2:13 settings-view:open (input.hidden-input)
     -1:45.5.0 core:backspace (input.hidden-input)
     -1:44.9.0 core:confirm (input.hidden-input)
     -1:36.5.0 pane:show-item-1 (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-Sids-Syntax-Theme.theme-atom-material-ui)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
apex-syntax 0.1.0 
apex-ui 0.2.1 
apex-ui-slim 0.0.0 
apm-publish 0.3.2 
atom-clock 0.1.9 
atom-html-preview 0.1.22 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
atom-pair 2.0.10 
printer 0.0.0 
atom-webbrowser 2.1.4 
atomify 0.3.0 
auto-indent-file 0.2.0 
autoclose-html 0.23.0 
autocomplete-clang 0.11.3 
autoupdate-packages 1.3.1 
busy-signal 1.4.3 
color-picker 2.2.5 
colorblind-wombat-dark-syntax 0.6.0 
config-import-export 0.3.1 
duotone-dark-syntax 2.1.0 
feedback 0.38.0 
file-icons undefined 
file-templates 0.2.0 
flex-tool-bar 0.12.0 
floobits 0.32.10 
gpp-compiler 3.0.7 
hey-pane 1.0.0 
intentions 1.1.2 
language-tex 0.4.0 
latex-autocomplete 1.0.0 
linter 2.2.0 
linter-clang 4.1.1 
linter-ui-default 1.6.1 
linter-write-good 0.9.0 
lipsum 0.1.0 
minimap 4.28.2 
minimap-pigments 0.2.2 
minimap-titles 1.11.0 
navigate 0.1.17 
no-title-bar 0.6.6 
package-sync-plus 0.1.2 
pdf-view 0.59.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
pristine-ui 1.0.15 
pure-syntax 0.2.1 
remote-atom 1.3.10 
Sids-Syntax-Theme 1.0.0 
slack-chat 3.4.2 
spell-check-test 0.77.5 
Sublime-Style-Column-Selection 1.7.4 
terminal-fusion 2.4.4 
terminal-plus 0.14.5 
tool-bar 1.1.0 
```

**Comment by lexcast** [comment]
Thanks @sidpagariya, now I see 1.19.0-beta0, that version changed the rendering layer of the text editor, I have a fix for it, I will release it soon.

**Comment by chenasraf** [comment]
I'm on beta too, waiting for fix :)

**Comment by sidpagariya** [comment]
Thanks @lexcast, it is working really well now! Thanks for being so quick in resolving this...
Have a great summer!

**Comment by COOLGAMETUBE** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: DESKTOP-U26DIDP
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package 2.0.0


### Stack Trace

Uncaught TypeError: Cannot read property 'appendChild' of null

```
At C:\Users\Simon\.atom\packages\activate-power-mode\lib\canvas-renderer.coffee:52

TypeError: Cannot read property 'appendChild' of null
    at Object.setupCanvas (/packages/activate-power-mode/lib/canvas-renderer.coffee:52:20)
    at Object.onChangePane (/packages/activate-power-mode/lib/plugin/power-canvas.coffee:15:13)
    at /packages/activate-power-mode/lib/plugin-manager.coffee:88:32
    at Object.onEnabled (/packages/activate-power-mode/lib/plugin-registry.coffee:64:19)
    at Object.runOnChangePane (/packages/activate-power-mode/lib/plugin-manager.coffee:87:21)
    at Object.setupPane (/packages/activate-power-mode/lib/power-editor.coffee:40:20)
    at /packages/activate-power-mode/lib/power-editor.coffee:9:8
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/workspace.js:551:30
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
language-lua 0.9.11 
```

**Comment by miaulightouch** [comment]
Atom 1.19.0 released.
and yes, it's broken.

**Comment by gwfowlcity** [comment]
just update  activate-power-mode to 2.2.0

**Comment by Jerajo** [comment]
> @gwfowlcity
    just update activate-power-mode to 2.2.0

@COOLGAMETUBE also you can  get the latest release for ATOM [here](https://github.com/atom/atom/releases/tag/v1.19.0).

**Comment by timendez** [comment]
Thanks @gwfowlcity, a power mode update and restarting atom worked for me

**Comment by sunlery** [comment]
Uncaught TypeError: Cannot read property 'appendChild' of null

C:\Users\Administrator\.atom\packages\activate-power-mode\lib\canvas-renderer.coffee:52

TypeError: Cannot read property 'appendChild' of null
    at Object.setupCanvas (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/canvas-renderer.coffee:52:20)
    at Object.onChangePane (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/plugin/power-canvas.coffee:15:13)
    at file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/plugin-manager.coffee:88:32
    at Object.onEnabled (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/plugin-registry.coffee:64:19)
    at Object.runOnChangePane (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/plugin-manager.coffee:87:21)
    at Object.setupPane (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/power-editor.coffee:40:20)
    at file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/power-editor.coffee:9:8
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Administrator\AppData\Local\atom\app-1.19.2\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.19.2\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at C:\Users\Administrator\AppData\Local\atom\app-1.19.2\resources\app\src\workspace.js:551:30

**Comment by Recai99** [comment]
I updated Atom and power mode, uninstalled the package and restarted atom. None helped.
