### ISSUE TITLE
Failed to activate the activate-power-mode package

### ISSUE THREAD

**Issue by wenwuchige** [JoelBesada/activate-power-mode#143]
when i finished installing,there occur an error:
Failed to activate the activate-power-mode package
undefined is not a function
Hide Stack Trace
TypeError: undefined is not a function
    at Object.module.exports.ActivatePowerMode.activate (C:\Users\dell\.atom\packages\activate-power-mode\lib\activate-power-mode.coffee:18:46)
    at Package.module.exports.Package.activateNow (C:\Users\dell\AppData\Local\atom\app-1.0.11\resources\app.asar\src\package.js:243:19)
    at C:\Users\dell\AppData\Local\atom\app-1.0.11\resources\app.asar\src\package.js:224:30
    at Package.module.exports.Package.measure (C:\Users\dell\AppData\Local\atom\app-1.0.11\resources\app.asar\src\package.js:167:15)
    at Package.module.exports.Package.activate (C:\Users\dell\AppData\Local\atom\app-1.0.11\resources\app.asar\src\package.js:216:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\dell\AppData\Local\atom\app-1.0.11\resources\app.asar\src\package-manager.js:486:21)
    at C:\Users\dell\AppData\Local\atom\app-1.0.11\resources\app.asar\src\package-manager.js:469:29
    at Config.module.exports.Config.transact (C:\Users\dell\AppData\Local\atom\app-1.0.11\resources\app.asar\src\config.js:324:16)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\dell\AppData\Local\atom\app-1.0.11\resources\app.asar\src\package-manager.js:464:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\dell\AppData\Local\atom\app-1.0.11\resources\app.asar\src\package-manager.js:445:46)

the version of my os is win7
and the version of activate-power-mode is 0.41
the way i install it as follows:
firstly,i download the zip release file and copy it to the path of packages of atom ,that is C:\Users\dell\AppData\Local\atom\packages in my pc
then i open the cmd.exe and input the command - apm install activate-power-mode
finaly ,i got a installing done message
but when i opened the atom ,the error occur, what should i do? thanks!

**Comment by ChiggerChug** [comment]
+1

**Comment by Lanceloft** [comment]
yes,i am

**Comment by Lanceloft** [comment]
+1

**Comment by lqxion** [comment]
+1

**Comment by briankwon** [comment]
+1

**Comment by vaninanton** [comment]
+1

**Comment by frousselet** [comment]
+1

**Comment by lexcast** [comment]
the version is 0.4.1? use the newest 0.5.2

**Comment by SijiaDavis** [comment]
same problem here

**Comment by lexcast** [comment]
there is a error when the package is updated, you need to restart atom

**Comment by chakzefir** [comment]
@lexcast thanks, pretty helped.

**Comment by codehz** [comment]
+1

**Comment by lexcast** [comment]
@wenwuchige you don't need to download the zip.
You can install the package just with your terminal `apm install activate-power-mode`
or from atom on Settings > Install > Search for activate-power-mode

I don't know if installing with the zip and then with apm is the problem for you.

**Comment by tianshanghuo** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Microsoft Windows 10 Home
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.5.2


### Stack Trace

Failed to activate the activate-power-mode package

```
At undefined is not a function

TypeError: undefined is not a function
    at Object.module.exports.ActivatePowerMode.activate (C:\Users\beargan\.atom\packages\activate-power-mode\lib\activate-power-mode.coffee:18:46)
    at Package.module.exports.Package.activateNow (C:\Users\beargan\AppData\Local\atom\app-1.0.11\resources\app.asar\src\package.js:243:19)
    at C:\Users\beargan\AppData\Local\atom\app-1.0.11\resources\app.asar\src\package.js:224:30
    at Package.module.exports.Package.measure (C:\Users\beargan\AppData\Local\atom\app-1.0.11\resources\app.asar\src\package.js:167:15)
    at Package.module.exports.Package.activate (C:\Users\beargan\AppData\Local\atom\app-1.0.11\resources\app.asar\src\package.js:216:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\beargan\AppData\Local\atom\app-1.0.11\resources\app.asar\src\package-manager.js:486:21)
    at C:\Users\beargan\AppData\Local\atom\app-1.0.11\resources\app.asar\src\package-manager.js:469:29
    at Config.module.exports.Config.transact (C:\Users\beargan\AppData\Local\atom\app-1.0.11\resources\app.asar\src\config.js:324:16)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\beargan\AppData\Local\atom\app-1.0.11\resources\app.asar\src\package-manager.js:464:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\beargan\AppData\Local\atom\app-1.0.11\resources\app.asar\src\package-manager.js:445:46)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2

# Dev
No dev packages
```

**Comment by Varkal** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.5.2


### Stack Trace

Failed to activate the activate-power-mode package

```
At Cannot read property 'parentNode' of undefined

TypeError: Cannot read property 'parentNode' of undefined
    at Object.module.exports.ActivatePowerMode.setupCanvas (/Users/romain.moreau/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:37:5)
    at Object.module.exports.ActivatePowerMode.activate (/Users/romain.moreau/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:22:7)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:389:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -0:14.8.0 core:close (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:10.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
emmet, v2.4.3
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by imisslovelove** [comment]
+1

**Comment by JetCrusherTorpedo** [comment]
+1

**Comment by Steague** [comment]
+1

**Comment by Cafune** [comment]
+1

**Comment by Aidoboy** [comment]
+1
Stack Trace:
```
Stack Trace
TypeError: Cannot read property 'classList' of undefined
    at Object.module.exports.ActivatePowerMode.activate (file:///C:/Users/Aidan/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:14:5)
    at Package.module.exports.Package.activateNow (C:\Users\Aidan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:183:20)
    at C:\Users\Aidan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\Aidan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:92:15)
    at C:\Users\Aidan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\Aidan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Aidan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\Aidan\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:389:60
    at exit (C:\Users\Aidan\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Aidan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\Aidan\AppData\Local\atom\app-1.7.3\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by webhacking** [comment]
:+1:

**Comment by nonameratnowhere** [comment]
+1
`[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.5
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.5.2


### Stack Trace

Failed to activate the activate-power-mode package

```
At Cannot read property 'parentNode' of undefined

TypeError: Cannot read property 'parentNode' of undefined
    at Object.module.exports.ActivatePowerMode.setupCanvas (/Users/weisun/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:37:5)
    at Object.module.exports.ActivatePowerMode.activate (/Users/weisun/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:22:7)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:389:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
 13x -2:00.7.0 core:move-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -1:57.2.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -1:55.3.0 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 26x -1:54.8.0 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  5x -1:49.3.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 13x -1:42.2.0 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  6x -1:40.2.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 25x -1:38.2.0 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:31.3.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:29.1.0 core:move-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:58.2.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:53.5.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:52.9.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:52.7.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:37.7.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:18.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
markdown-preview-opener, v0.1.1

# Dev
No dev packages
```

`

**Comment by skmn7** [comment]
+1

**Comment by pkumza** [comment]
+1

**Comment by liyouvane** [comment]
+1

**Comment by geymed** [comment]
👍

**Comment by lylayueting** [comment]
+1
Installed through apm, failed when open Atom

**Comment by aipame** [comment]
+1

**Comment by kamlekar** [comment]
I don't know why people still using `+1` when they can upvote a post \_(ツ)_/¯

**Comment by Cafune** [comment]
@kamlekar +1

**Comment by frogman544** [comment]
+1

**Comment by ppetermann** [comment]
+1

**Comment by androiddeveloper1993** [comment]
+1

**Comment by lexcast** [comment]
Closing as this was caused (mostly) by an issue updating the package.

I think is gone, but just reload atom if this issue appears right after update the package.

**Comment by EasyWalk** [comment]
+1

**Comment by Newpostlogger** [comment]
+5

**Comment by ArdentKid** [comment]
+1

**Comment by SignVOVA** [comment]
Restarting Atom fixes the issue, well error messait just dissapers.

**Comment by Tig10** [comment]
Restarting Atom has not fixed issue for me. :(

**Comment by BonLeung** [comment]
+1

**Comment by blackwhite2417** [comment]
+1

**Comment by zxj453184788** [comment]
+1

**Comment by SunGodAppollo** [comment]
+1

**Comment by emcai** [comment]
Getting the same issue. Quitting/restarting atom multiple times doesn't help. Running Mac OS 10.13.5 High Sierra

**Comment by 201200301301** [comment]
+1

**Comment by wjdwithyou** [comment]
+1
