### ISSUE TITLE
Uncaught TypeError: Cannot set property 'undefined' of undefined

### ISSUE THREAD

**Issue by Allen5** [JoelBesada/activate-power-mode#147]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.5.2

### Stack Trace

Uncaught TypeError: Cannot set property 'undefined' of undefined

```
At /Users/wuwenqing/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:62

TypeError: Cannot set property 'undefined' of undefined
    at Object.module.exports.ActivatePowerMode.spawnParticles (/Users/wuwenqing/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:62:42)
    at Object.debounced [as throttledSpawnParticles] (/Users/wuwenqing/.atom/packages/activate-power-mode/node_modules/lodash.throttle/node_modules/lodash.debounce/index.js:182:23)
    at Object.module.exports.ActivatePowerMode.onChange (/Users/wuwenqing/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:38:6)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:692:27)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:877:16)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:831:14)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1274:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:868:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2170:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2132:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:866:19)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:832:19)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:474:35)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)
```

### Commands

```
     -0:08.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:08.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:07.9.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:07.9.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -0:05.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:05.4.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused)
  2x -0:05.4.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:04.6.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused.power-mode)
     -0:04.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused.power-mode)
     -0:04.5.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused.power-mode)
  2x -0:04.2.0 core:move-down (atom-text-editor.editor.is-focused.power-mode)
     -0:04.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused.power-mode)
     -0:04.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused.power-mode)
  2x -0:03.8.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused.power-mode)
     -0:03.3.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused.power-mode)
     -0:03.2.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused.power-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "w3c-validation"
    ],
    "projectHome": "/Users/wuwenqing/Work",
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2

# Dev
No dev packages
```

**Comment by lexcast** [comment]
@Allen5 how can that error be reproduced?

**Comment by Allen5** [comment]
@lexcast when I upgrade the plugin from the atom's setting panel

**Comment by lexcast** [comment]
so, when you restart atom the package works?

**Comment by Allen5** [comment]
yeah, It works. So what is the reason?

**Comment by lexcast** [comment]
The package wasn't closing itself properly on the upgrade, I've made some fixes on the deactivate method to solve this on future releases, I hope it works.

**Comment by Allen5** [comment]
@lexcast Hah, good job, man. I love this package, it is so nice.
