### ISSUE TITLE
Uncaught TypeError: deprecationSite.getFileName is not a function

### ISSUE THREAD

**Issue by Miloas** [JoelBesada/activate-power-mode#15]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.3.2

### Stack Trace

Uncaught TypeError: deprecationSite.getFileName is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56

TypeError: deprecationSite.getFileName is not a function
    at Object.global.__grim__.deprecate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56:36)
    at TextEditor.module.exports.TextEditor.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2747:12)
    at Object.module.exports.ActivatePowerMode.spawnParticles (/Users/Genesis/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:67:27)
    at Object.debounced [as throttledSpawnParticles] (/Users/Genesis/.atom/packages/activate-power-mode/node_modules/lodash.throttle/node_modules/lodash.debounce/index.js:182:23)
    at Object.module.exports.ActivatePowerMode.onChange (/Users/Genesis/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:48:6)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:645:20)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:799:16)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:768:14)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1152:26)
```

### Commands

```
     -0:12.2.0 activate-power-mode:toggle (atom-text-editor.editor.is-focused.vim-mode.normal-mode.power-mode)
     -0:11.3.0 vim-mode:activate-insert-mode (atom-text-editor.editor.is-focused.vim-mode.normal-mode.power-mode)
     -0:06.7.0 activate-power-mode:toggle (atom-text-editor.editor.is-focused.vim-mode.power-mode.insert-mode)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.3.2
autocomplete-clang, v0.8.8
autocomplete-python, v0.10.4
color-picker, v2.0.13
go-plus, v3.5.2
hyperclick, v0.0.32
nuclide-flow, v0.0.32
nuclide-hack, v0.0.32
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by Miloas** [comment]
oh ,I uninstall nuclide package ,and all is ok.
