### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by JasonAn** [JoelBesada/activate-power-mode#158]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 15.04
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.5.2

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:833

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/opt/atom/resources/app.asar/src/display-buffer.js:794:15)
    at TextEditor.module.exports.TextEditor.screenPositionForBufferPosition (/opt/atom/resources/app.asar/src/text-editor.js:1363:33)
    at Object.module.exports.ActivatePowerMode.spawnParticles (/home/jason/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:99:30)
    at Object.debounced [as throttledSpawnParticles] (/home/jason/.atom/packages/activate-power-mode/node_modules/lodash.throttle/node_modules/lodash.debounce/index.js:182:23)
    at Object.module.exports.ActivatePowerMode.onChange (/home/jason/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:75:8)
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:692:27)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:602:12)
    at /opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:576:26
    at TextBuffer.module.exports.TextBuffer.transact (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:574:21)
    at TextBuffer.module.exports.TextBuffer.setText (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:514:19)
    at TextEditor.module.exports.TextEditor.setText (/opt/atom/resources/app.asar/src/text-editor.js:810:26)
    at DiffViewEditor.cleanUp (/home/jason/.atom/packages/split-diff/lib/build-lines.js:179:20)
    at Object.module.exports.SplitDiff.disable (/home/jason/.atom/packages/split-diff/lib/split-diff.coffee:75:26)
    at /home/jason/.atom/packages/split-diff/lib/split-diff.coffee:183:8
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.destroyed (/opt/atom/resources/app.asar/src/text-editor.js:295:27)
    at TextEditor.module.exports.Model.destroy (/opt/atom/resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (/opt/atom/resources/app.asar/src/pane.js:639:18)
    at atom-tabs.TabBarView.onClick (/opt/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:688:17)
```

### Commands

```
     -0:22.2.0 split-diff:toggle (ul.list-inline.tab-bar.inset-panel)
     -0:18.1.0 tree-view:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused.power-mode)
```

### Config

```json
{
  "core": {},
  "activate-power-mode": {
    "particles": {
      "size": {},
      "spawnCount": {},
      "totalCount": {}
    },
    "screenShake": {}
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
markdown-preview-plus, v2.4.0
minimap-split-diff, v0.3.1
split-diff, v1.0.2
vim-mode, v0.65.1

# Dev
No dev packages
```

**Comment by hawsome** [comment]
uninstall `split-diff`

**Comment by lexcast** [comment]
Hi @JasonAn 

Can you reproduce this issue with the latest release?

**Comment by lexcast** [comment]
Closing issues on old versions of this package.

Open again if the problem persists with the latest release.
