### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by VolVoz** [JoelBesada/activate-power-mode#159]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: "Fedora release
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.5.2

### Stack Trace

Uncaught TypeError: Cannot read property 'querySelector' of null

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:833

TypeError: Cannot read property 'querySelector' of null
    at Object.module.exports.ActivatePowerMode.calculateCursorOffset (/home/volvoz/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:60:47)
    at Object.module.exports.ActivatePowerMode.spawnParticles (/home/volvoz/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:100:21)
    at Object.debounced [as throttledSpawnParticles] (/home/volvoz/.atom/packages/activate-power-mode/node_modules/lodash.throttle/node_modules/lodash.debounce/index.js:182:23)
    at Object.module.exports.ActivatePowerMode.onChange (/home/volvoz/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:75:8)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:692:27)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:602:12)
    at Selection.module.exports.Selection.insertText (/usr/share/atom/resources/app.asar/src/selection.js:483:43)
    at /usr/share/atom/resources/app.asar/src/text-editor.js:835:29
    at /usr/share/atom/resources/app.asar/src/text-editor.js:874:29
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1328:26)
    at /usr/share/atom/resources/app.asar/src/text-editor.js:868:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:2220:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:2186:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/share/atom/resources/app.asar/src/text-editor.js:866:19)
    at TextEditor.module.exports.TextEditor.insertText (/usr/share/atom/resources/app.asar/src/text-editor.js:832:19)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/usr/share/atom/resources/app.asar/src/text-editor-component.js:504:26)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/src/text-editor-component.js:3:61)
```

### Commands

```
     -2:22.3.0 core:confirm (input.hidden-input)
     -1:52.9.0 editor:newline (input.hidden-input)
     -1:50.7.0 core:undo (input.hidden-input)
  3x -1:49 editor:newline (input.hidden-input)
undefined -0:55 core:backspace (input.hidden-input)
     -0:12.9.0 snippets:next-tab-stop (input.hidden-input)
     -0:12.9.0 snippets:expand (input.hidden-input)
     -0:12.8.0 editor:indent (input.hidden-input)
     -0:11.5.0 snippets:next-tab-stop (input.hidden-input)
     -0:11.5.0 snippets:expand (input.hidden-input)
     -0:11.5.0 editor:indent (input.hidden-input)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "pep8",
      "autocomplete-plus-python-jedi",
      "rst-preview",
      "python-autopep8",
      "linter-python-pep257",
      "linter-pep8",
      "power-mode"
    ],
    "ignoredNames": [
      ".pyc"
    ]
  },
  "activate-power-mode": {
    "particles": {
      "size": {},
      "spawnCount": {},
      "totalCount": {}
    },
    "screenShake": {}
  }
}
```

### Installed Packages

```coffee
# User
MagicPython, v0.5.11
activate-power-mode, v0.5.2
atom-beautify, v0.29.7
autocomplete-python, v1.7.3
file-icons, v1.7.13
fonts, v1.5.0
highlight-selected, v0.11.2
language-buildout, v0.1.1
linter, v1.11.4
linter-flake8, v1.13.0
linter-python-pep8, v0.2.0
linter-solidity, v0.2.1
minimap-find-and-replace, v4.5.1
pretty-json, v1.4.0
python-indent, v0.4.3
python-iresolve, v0.0.3
python-tools, v0.6.7
rst-preview-pandoc, v0.1.12
terminal-plus, v0.14.5
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by motasimhussain** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.5.2


### Stack Trace

Uncaught TypeError: Cannot read property 'querySelector' of null

```
At C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:833

TypeError: Cannot read property 'querySelector' of null
    at Object.module.exports.ActivatePowerMode.calculateCursorOffset (file:///C:/Users/Motasim/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:60:47)
    at Object.module.exports.ActivatePowerMode.spawnParticles (file:///C:/Users/Motasim/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:100:21)
    at Object.debounced [as throttledSpawnParticles] (C:\Users\Motasim\.atom\packages\activate-power-mode\node_modules\lodash.throttle\node_modules\lodash.debounce\index.js:182:23)
    at Object.module.exports.ActivatePowerMode.onChange (file:///C:/Users/Motasim/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:75:8)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:692:27)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:602:12)
    at Selection.module.exports.Selection.insertText (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\src\selection.js:483:43)
    at C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:835:29
    at C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:874:29
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:828:18)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:1328:26)
    at C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:868:24
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:2220:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:2186:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:866:19)
    at TextEditor.module.exports.TextEditor.insertText (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:832:19)
    at TextEditor.object.(anonymous function) [as insertText] (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor-component.js:504:26)
    at HTMLDivElement.<anonymous> (C:\Users\Motasim\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor-component.js:3:61)
```

### Commands

```
  8x -3:42.1.0 core:backspace (input.hidden-input)
     -3:40.2.0 core:confirm (input.hidden-input)
     -2:19.6.0 command-palette:toggle (atom-text-editor.editor.is-focused.power-mode)
     -2:14.6.0 editor:consolidate-selections (input.hidden-input)
     -2:14.6.0 core:cancel (input.hidden-input)
  3x -2:12.7.0 project-plus:toggle-project-finder (atom-text-editor.editor.power-mode.is-focused)
     -1:26.2.0 activate-power-mode:toggle (atom-pane.pane.active)
     -1:10.3.0 core:backspace (input.hidden-input)
     -1:07.0 command-palette:toggle (input.hidden-input)
     -1:03.0 activate-power-mode:toggle (input.hidden-input)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "quantum-shell",
      "esformatter"
    ],
    "themes": [
      "one-dark-ui",
      "improved-chester-atom-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
auto-detect-indentation, v1.1.0
autoclose-html, v0.23.0
codeigniter, v0.3.0
emmet, v2.4.3
fonts, v1.5.0
highlight-selected, v0.11.2
improved-chester-atom-syntax, v0.2.0
javascript-snippets, v1.2.1
linter, v1.11.14
linter-csslint, v1.3.2
linter-htmlhint, v1.2.1
linter-jshint, v2.1.0
open-recent, v5.0.0
php-cs-fixer, v2.5.6
pigments, v0.29.2
project-plus, v0.9.0
Remote-FTP, v0.7.20
rest-client, v1.1.1
wordpress-api, v1.2.2

# Dev
No dev packages
```

**Comment by guisouza** [comment]
Try to activate shadow-dom in your atom preferences, it should fix it.

**Comment by lexcast** [comment]
Support for non shadow-dom was added since 0.7.0 release
