### ISSUE TITLE
activate-power-mode

### ISSUE THREAD

**Issue by holidaying** [JoelBesada/activate-power-mode#165]
TypeError: undefined is not a function
  at Object.module.exports.enable (C:\Users\Administrator.atom\packages\activate-power-mode\lib\power-editor.coffee:12:46)
  at Object.module.exports.ActivatePowerMode.toggle (C:\Users\Administrator.atom\packages\activate-power-mode\lib\activate-power-mode.coffee:30:34)
  at atom-workspace.subscriptions.add.atom.commands.add.activate-power-mode:toggle (C:\Users\Administrator.atom\packages\activate-power-mode\lib\activate-power-mode.coffee:15:41)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (D:\Documents\Downloads\atom-windows\Atom\resources\app\src\command-registry.js:242:29)
  at D:\Documents\Downloads\atom-windows\Atom\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (D:\Documents\Downloads\atom-windows\Atom\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:552:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (D:\Documents\Downloads\atom-windows\Atom\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:392:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (D:\Documents\Downloads\atom-windows\Atom\resources\app\src\window-event-handler.js:180:20)

**Comment by lexcast** [comment]
@holidaying how can you reproduce this issue?

**Comment by lexcast** [comment]
Closing for lack of activity, Open again if the issue persist with the latest release.
