### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Awdesh** [JoelBesada/activate-power-mode#168]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.184.0
**System**: linux 4.4.0-28-generic
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.7.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/awdesh/.atom/packages/activate-power-mode/lib/power-editor.coffee:12

TypeError: undefined is not a function
  at Object.module.exports.enable (/home/awdesh/.atom/packages/activate-power-mode/lib/power-editor.coffee:12:46)
  at Object.module.exports.ActivatePowerMode.toggle (/home/awdesh/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:30:34)
  at atom-workspace.subscriptions.add.atom.commands.add.activate-power-mode:toggle (/home/awdesh/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:15:41)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:75:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
     -0:24.3 activate-power-mode:toggle (atom-text-editor.editor.is-focused)
 16x -0:22.8 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.7 activate-power-mode:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0

# Dev
No dev packages
```

**Comment by lexcast** [comment]
it's really atom version 0.184.0?
If it is, please upgrade atom and try the package

**Comment by xmxstudio** [comment]
Same Error on Kubuntu 16.04 + Atom 1.0.11

**Comment by lexcast** [comment]
@Awdesh @xmxstudio How can you reproduce this issue?

**Comment by xmxstudio** [comment]
not sure. just upgraded atom to 1.10.0 and problem solved.

**Comment by Awdesh** [comment]
@lexcast 
install plugin. 
Restart Atom. 
Click on Toggle from menu bar.

As above I'm using above Atom version 0.184.0. So not sure if it's still same issue in 1.0.11.

**Comment by lexcast** [comment]
Seems that onDidStopChangingActivePaneItem function was added on Atom 1.1 or 1.2, atom/atom#9029. @Awdesh The solution is update Atom to the latest release.

**Comment by Awdesh** [comment]
Cool. Thanks. Just updated to 1.10.0 and don't see issue anymore..

**Comment by iamehis** [comment]
i have the same issue.
