### ISSUE TITLE
Error:Cannot find module 'lodash.throttle'

### ISSUE THREAD

**Issue by qianshuijun** [JoelBesada/activate-power-mode#17]
when i press ctrl+alt+o 

atom call attention to me 

Failed to activate the activate-power-mode package
Cannot find module 'lodash.throttle'
Hide Stack Trace
Error: Cannot find module 'lodash.throttle'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\qians_000\AppData\Local\atom\app-1.2.4\lib\net45\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (<anonymous>:1:12)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\qians_000\AppData\Local\atom\app-1.2.4\lib\net45\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)

**Comment by Norcy** [comment]
You should download the lodash module by yourself.
By the way, you had better download the nodejs including npm first, and use the npm to download lodash module.

**Comment by zhmocean** [comment]
```
cd ~/.atom/packages/activate-power-mode
npm install lodash --save
npm install lodash.throttle --save 
```

**Comment by lexcast** [comment]
try installing with your terminal: `apm install activate-power-mode`
