### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'querySelector' on 'DocumentFragment': '.markup.underline.link..hyperlink' is not a valid selector.

### ISSUE THREAD

**Issue by wigvp** [JoelBesada/activate-power-mode#179]
Today the following error message popped up. I don't remember doing anything special. Code is in HTML.

**Atom Version**: 1.9.6
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.7.2

### Stack Trace

Uncaught SyntaxError: Failed to execute 'querySelector' on 'DocumentFragment': '.markup.underline.link..hyperlink' is not a valid selector.

```
At C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:852

Error: Failed to execute 'querySelector' on 'DocumentFragment': '.markup.underline.link..hyperlink' is not a valid selector.
    at Error (native)
    at Object.module.exports.getColorAtPosition (file:///C:/Users/user/.atom/packages/activate-power-mode/lib/power-canvas.coffee:53:55)
    at Object.module.exports.spawnParticles (file:///C:/Users/user/.atom/packages/activate-power-mode/lib/power-canvas.coffee:43:14)
    at invokeFunc (C:\Users\user\.atom\packages\activate-power-mode\node_modules\lodash.throttle\index.js:149:19)
    at leadingEdge (C:\Users\user\.atom\packages\activate-power-mode\node_modules\lodash.throttle\index.js:159:22)
    at Cursor.debounced [as throttleSpawnParticles] (C:\Users\user\.atom\packages\activate-power-mode\node_modules\lodash.throttle\index.js:224:16)
    at Object.module.exports.onChange (file:///C:/Users/user/.atom/packages/activate-power-mode/lib/power-editor.coffee:56:14)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:711:27)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:621:12)
    at Selection.module.exports.Selection.insertText (C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\src\selection.js:480:43)
    at C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\src\text-editor.js:934:29
    at C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\src\text-editor.js:973:29
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:847:18)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\src\text-editor.js:1390:26)
    at C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\src\text-editor.js:967:24
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\src\text-editor.js:2369:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\src\text-editor.js:2331:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\src\text-editor.js:965:19)
    at TextEditor.module.exports.TextEditor.insertText (C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\src\text-editor.js:931:19)
    at TextEditor.object.(anonymous function) [as insertText] (C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\src\text-editor-component.js:506:26)
    at HTMLDivElement.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.9.6\resources\app.asar\src\text-editor-component.js:3:61)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (active)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.3 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

Restart / update didn't help.

**Comment by lexcast** [comment]
Do you have Shadow DOM enabled?

**Comment by lexcast** [comment]
tell if the fix is working for you

**Comment by wigvp** [comment]
Great, it's working now. Thanks @lexcast. :-)

**Comment by lexcast** [comment]
Great, thanks.
