### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Element': '.markup.underline.link.rfc.7.hyperlink' is not a valid selector.

### ISSUE THREAD

**Issue by aaronjamesmarshallau** [JoelBesada/activate-power-mode#185]
### Steps to Reproduce
1. Open any file with 'activate-power-mode' enabled.
2. Type a space, followed by 'RFC' and any number. (ex: ' RFC7915')
3. Error will be shown in error popup (generated by Atom)
4. Cry.

**Atom Version**: 1.9.8
**System**: Microsoft Windows 10 Pro
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.7.4

### Stack Trace

Uncaught SyntaxError: Failed to execute 'querySelector' on 'Element': '.markup.underline.link.rfc.7.hyperlink' is not a valid selector.

```
At C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:873

Error: Failed to execute 'querySelector' on 'Element': '.markup.underline.link.rfc.7.hyperlink' is not a valid selector.
    at Error (native)
    at Object.module.exports.getColorAtPosition (file:///C:/Users/user/.atom/packages/activate-power-mode/lib/power-canvas.coffee:53:55)
    at Object.module.exports.spawnParticles (file:///C:/Users/user/.atom/packages/activate-power-mode/lib/power-canvas.coffee:43:14)
    at invokeFunc (C:\Users\user\.atom\packages\activate-power-mode\node_modules\lodash.throttle\index.js:149:19)
    at leadingEdge (C:\Users\user\.atom\packages\activate-power-mode\node_modules\lodash.throttle\index.js:159:22)
    at Cursor.debounced [as throttleSpawnParticles] (C:\Users\user\.atom\packages\activate-power-mode\node_modules\lodash.throttle\index.js:224:16)
    at Object.module.exports.onChange (file:///C:/Users/user/.atom/packages/activate-power-mode/lib/power-editor.coffee:56:14)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:729:20)
    at TextBuffer.module.exports.TextBuffer.applyChange (C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:714:19)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:623:12)
    at Selection.module.exports.Selection.insertText (C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\src\selection.js:480:43)
    at C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\src\text-editor.js:934:29
    at C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\src\text-editor.js:973:29
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:868:18)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\src\text-editor.js:1390:26)
    at C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\src\text-editor.js:967:24
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\src\text-editor.js:2365:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\src\text-editor.js:2331:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\src\text-editor.js:965:19)
    at TextEditor.module.exports.TextEditor.insertText (C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\src\text-editor.js:931:19)
    at TextEditor.object.(anonymous function) [as insertText] (C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\src\text-editor-component.js:506:26)
    at HTMLDivElement.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.9.8\resources\app.asar\src\text-editor-component.js:3:61)
```

### Commands

```
     -1:01.5.0 editor:newline (input.hidden-input)
     -0:52.3.0 core:save (input.hidden-input)
     -0:40.1.0 core:backspace (input.hidden-input)
  5x -0:36.7.0 core:move-left (input.hidden-input)
 53x -0:35.7.0 core:delete (input.hidden-input)
     -0:30 core:undo (input.hidden-input)
 20x -0:29.1.0 core:delete (input.hidden-input)
     -0:20.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
  5x -0:18.6.0 core:select-left (input.hidden-input)
     -0:16.8.0 core:move-right (input.hidden-input)
  4x -0:16.6.0 core:move-left (input.hidden-input)
     -0:15.5.0 core:select-left (input.hidden-input)
  2x -0:15 core:backspace (input.hidden-input)
     -0:11.9.0 core:move-left (input.hidden-input)
     -0:11.6.0 editor:select-to-end-of-line (input.hidden-input)
     -0:11.4.0 core:delete (input.hidden-input)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "autocomplete-haxe"
    ],
    "projectHome": "D:\\Development\\HTML",
    "themes": [
      "atom-material-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.4 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.3 (active)
autoclose-html, v0.23.0 (active)
autocomplete-haxe, v0.2.0 (inactive)
autocomplete-php, v0.3.7 (active)
color-picker, v2.2.2 (active)
firewatch-syntax, v1.0.1 (inactive)
fizzy-syntax-theme, v0.9.0 (inactive)
fonts, v1.6.0 (active)
jquery-snippets, v11.0.0 (active)
jshint, v1.8.5 (active)
linter, v1.11.16 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.24.7 (active)
piatto-light, v2.0.2 (inactive)
project-manager, v2.9.7 (active)
two-light-ui, v1.1.0 (inactive)
uglify, v1.2.5 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (active)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by lexcast** [comment]
That's weird, given that call is inside a try/catch block.

Did that happen just after you update the package? if so, try to reproduce the issue again

**Comment by aaronjamesmarshallau** [comment]
My apologies for the lack of response, @lexcast. I haven't had the issue in any of my installs of Atom since. I think it was to do with an issue of linking to RFCs when noted in code. I believe it is no longer an issue. Thanks for you help, anyway.
