### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by maxwellzdeamon** [JoelBesada/activate-power-mode#188]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.0-dev-ac75135
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Users/jeremy/.atom/packages/activate-power-mode/lib/power-editor.coffee:32

TypeError: Cannot read property 'split' of undefined
    at Object.module.exports.prepareEditor (/Users/jeremy/.atom/packages/activate-power-mode/lib/power-editor.coffee:32:32)
    at Object.module.exports.subscribeToActiveTextEditor (/Users/jeremy/.atom/packages/activate-power-mode/lib/power-editor.coffee:25:6)
    at /Users/jeremy/.atom/packages/activate-power-mode/lib/power-editor.coffee:13:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at stoppedChangingActivePaneItemCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:350:36)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "one-dark-ui",
      "textmate-tomorrow-night-blue-syntax"
    ],
    "useCustomTitleBar": true
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.8.0 (active)
apathy-theme, v1.10.6 (inactive)
atom-beautify, v0.29.10 (inactive)
atom-material-ui, v1.3.5 (inactive)
atom-spring-green-syntax, v1.1.12 (inactive)
atom-spring-green-ui, v1.1.8 (inactive)
atom-surfs-up-ui, v0.1.0 (inactive)
atom-toychest, v0.3.0 (inactive)
atom-ubuntu-dark-ui, v0.37.0 (inactive)
aurora-atom-syntax, v2.5.0 (inactive)
autocomplete-clang, v0.9.4 (active)
autoupdate-packages, v1.3.1 (active)
block-travel, v1.0.5 (active)
blue-dream-ui, v0.35.0 (inactive)
blue-sea-syntax, v0.1.0 (inactive)
cold-ui, v1.4.0 (inactive)
cowabunga, v0.2.0 (inactive)
expose, v0.12.1 (inactive)
forest-syntax, v1.8.0 (inactive)
ForLatex, v0.1.0 (inactive)
fuzzy-theme-switcher, v1.0.0 (inactive)
Glacier-Green-ui, v0.5.0 (inactive)
isotope-ui, v2.7.1 (inactive)
kimbie-dark, v1.3.1 (inactive)
kimbie-light, v1.3.1 (inactive)
kingfisher-syntax, v0.2.1 (inactive)
language-latex, v0.6.1 (inactive)
latex, v0.35.0 (inactive)
latexer, v0.3.0 (active)
linter, v1.11.16 (active)
linter-xo, v0.16.0 (active)
lychee-theme, v1.0.5 (inactive)
material, v2.2.0 (inactive)
material-ui, v1.0.9 (inactive)
minimap, v4.24.7 (active)
minimap-autohide, v0.10.1 (active)
molecule-ubuntu, v0.2.0 (inactive)
monokai-seti, v0.7.0 (inactive)
multi-theme-applicator, v0.8.0 (inactive)
naturegreen-dark-syntax, v0.1.1 (inactive)
neon-color-scheme, v1.0.0 (inactive)
pdf-view, v0.50.0 (active)
purple-haze-syntax, v1.5.0 (inactive)
purplest-inc-dark-ui, v1.0.0 (inactive)
quantum-ui, v0.3.0 (inactive)
razor-atom-syntax-theme, v2.2.3 (inactive)
remote-atom, v1.3.9 (active)
seti-ui, v1.3.2 (inactive)
skies-a-blue, v1.0.4 (inactive)
space-cowboy-syntax, v1.8.0 (inactive)
spacegray-tomorrowdark-ui, v1.0.0 (inactive)
ssh-config, v0.10.1 (inactive)
sync-settings, v0.7.2 (active)
textmate-tomorrow-night-blue-syntax, v0.2.0 (active)
theme-reel, v1.2.0 (inactive)
tinacious-design-syntax, v1.0.0 (inactive)
tron-green-ui, v0.7.0 (inactive)
vivid, v1.1.7 (inactive)
wombat-fixed, v3.1.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.6.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.1 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.3 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.1 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by lexcast** [comment]
How can you reproduce this issue?
