### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by iamehiz** [JoelBesada/activate-power-mode#237]
> /home/familylaptop/.atom/packages/activate-power-mode/lib/power-editor.coffee:17
> Hide Stack Trace
> TypeError: undefined is not a function
>   at Object.module.exports.enable (/home/familylaptop/.atom/packages/activate-power-mode/lib/power-editor.coffee:17:46)
>   at Object.module.exports.ActivatePowerMode.enable (/home/familylaptop/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:36:18)
>   at Object.module.exports.ActivatePowerMode.toggle (/home/familylaptop/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:32:38)
>   at atom-workspace.subscriptions.add.atom.commands.add.activate-power-mode:toggle (/home/familylaptop/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:16:42)
>   at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:245:29)
>   at /opt/atom/resources/app.asar/src/command-registry.js:3:61
>   at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
>   at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
>   at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:184:20)
> 

How will i solve this?

**Comment by lexcast** [comment]
how can you reproduce this issue?

**Comment by Jerajo** [comment]
I think that is auto generated by Atom.

**Comment by lexcast** [comment]
Closing for lack of activity, Open again if the issue persist with the latest release.
