### ISSUE TITLE
Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value).elementFromPoint is not a function

### ISSUE THREAD

**Issue by fstar** [JoelBesada/activate-power-mode#249]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v1.2.0

### Stack Trace

Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value).elementFromPoint is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:872

TypeError: (intermediate value)(intermediate value)(intermediate value).elementFromPoint is not a function
    at Object.getColorAtPosition (/Users/fuxin/.atom/packages/activate-power-mode/lib/power-canvas.coffee:51:49)
    at Object.spawnParticles (/Users/fuxin/.atom/packages/activate-power-mode/lib/power-canvas.coffee:43:14)
    at invokeFunc (/Users/fuxin/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:149:19)
    at leadingEdge (/Users/fuxin/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:159:22)
    at Cursor.debounced [as throttleSpawnParticles] (/Users/fuxin/.atom/packages/activate-power-mode/node_modules/lodash.throttle/index.js:224:16)
    at Object.onChange (/Users/fuxin/.atom/packages/activate-power-mode/lib/power-editor.coffee:57:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:728:20)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:713:19)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:622:12)
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:480:43)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1110:29
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1149:28
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:867:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1566:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1143:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2540:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2506:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1141:19)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1107:19)
    at TextEditor.object.(anonymous function) (/Users/fuxin/.atom/packages/language-babel/lib/insert-nl-jsx.coffee:31:18)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:478:26)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:59)
```

### Commands

```
     -7:48.1.0 activate-power-mode:toggle (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  2x -7:45.5.0 core:backspace (input.hidden-input)
     -7:35.3.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  2x -5:49.5.0 core:paste (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -2:23.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:38.5.0 settings-view:open (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:35.2.0 core:cancel (div.package-detail.panels-item)
     -1:10.8.0 core:close (input#activate-power-mode.screenShake.enabled.)
     -0:54.5.0 activate-power-mode:toggle (input.hidden-input)
     -0:47.3.0 editor:consolidate-selections (input.hidden-input)
     -0:47.3.0 core:cancel (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-flake8",
      "autocomplete-python"
    ],
    "telemetryConsent": "no",
    "themes": [
      "seti-ui",
      "atom-monokai"
    ]
  },
  "activate-power-mode": {
    "screenShake": {}
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.2.0 (active)
aligner, v0.22.3 (active)
aligner-python, v1.0.1 (active)
angularjs, v0.3.5 (active)
angularjs-snippets, v0.10.18 (active)
atom-beautify, vundefined (active)
atom-fix-path, v0.1.0 (active)
atom-html-preview, v0.1.22 (active)
atom-icons, v0.2.2 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.3 (inactive)
atom-miku, v2.2.5 (active)
atom-monokai, v0.10.4 (active)
atom-react-autocomplete, v0.1.10 (active)
atom-react-native-autocomplete, v0.0.27 (active)
autocomplete-js-import, v1.2.1 (active)
autocomplete-modules, v1.6.7 (active)
autocomplete-python, v1.8.4 (inactive)
emmet-jsx-css-modules, v1.0.0 (active)
js-func-viewer, v1.0.5 (active)
language-babel, v2.45.0 (active)
language-javascript-jsx, v0.3.7 (active)
linter, v1.11.18 (active)
linter-flake8, v2.1.4 (inactive)
lunar-particle-ui, v0.3.13 (inactive)
markdown-preview-plus, v2.4.0 (active)
markdown-themeable-pdf, v1.2.0 (active)
minimap, v4.25.7 (active)
platformio-ide-terminal, v2.2.2 (active)
python-tools, v0.6.8 (active)
react-es6-snippets, v0.3.0 (active)
react-snippets, v0.5.0 (active)
remote-edit, v1.8.24 (active)
Remote-FTP, v0.8.3 (active)
remote-sync, v4.1.2 (active)
script, v3.8.3 (inactive)
seti-ui, v1.3.2 (active)
svg-preview, v0.10.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```
I can`t type anything when using activate-power-mode. how can i solve this?

**Comment by lexcast** [comment]
how you reproduce this?

**Comment by fstar** [comment]
e ....now It can be used again...  i don`t know what happend... may be the reason for the operating system?
