### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ShangguanMr** [JoelBesada/activate-power-mode#258]
TypeError: Cannot read property 'appendChild' of null
    at Object.setup (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/combo-mode.coffee:56:48)
    at Object.prepareEditor (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/power-editor.coffee:53:16)
    at Object.subscribeToActiveTextEditor (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/power-editor.coffee:41:6)
    at Object.enable (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/power-editor.coffee:27:6)
    at Object.enable (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:38:18)
    at Object.toggle (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:34:38)
    at Object.activate (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:23:8)
    at Package.module.exports.Package.activateNow (C:\Users\Administrator\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:184:19)
    at C:\Users\Administrator\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:157:32
    at Package.module.exports.Package.measure (C:\Users\Administrator\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:92:15)
    at C:\Users\Administrator\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:150:26
    at Package.module.exports.Package.activate (C:\Users\Administrator\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Administrator\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\Administrator\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (C:\Users\Administrator\AppData\Local\atom\app-1.12.7\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Administrator\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\Administrator\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package-manager.js:508:46)
    at C:\Users\Administrator\AppData\Local\atom\app-1.12.7\resources\app.asar\src\atom-environment.js:792:28

**Comment by lexcast** [comment]
Hi @ShangguanMr 
Can you provide steps to reproduce the issue?

**Comment by lexcast** [comment]
Closing for lack of activity, Open again if the issue persist with the latest release.
