### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by ls69knight** [JoelBesada/activate-power-mode#261]
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.4.5 | darwin | x64
gyp http GET https://atom.io/download/electron/v1.3.13/iojs-v1.3.13.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: connect ETIMEDOUT 52.216.64.216:443
gyp ERR! stack     at Object.exports._errnoException (util.js:870:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:893:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=1.3.13" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/lidoujun/.atom
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by XTpeeps** [comment]
the same to u, how to fix it..

**Comment by lexcast** [comment]
Hi @ls69knight 
How are you installing the package?
That's seems like a problem with something else.

**Comment by MerleLK** [comment]
you can use Offline installation to install those package.....

**Comment by lexcast** [comment]
Closing for lack of activity, Open again if the issue persist with the latest release.
And yes, seems like a network problem.

**Comment by awbacker** [comment]
Just a note, I was having this as well and now its gone.  Perhaps it really is a network issue, but i'd suspect some silliness in node on osx.  Really no idea why, though.

```
Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@7.10.1 | darwin | x64
gyp http GET https://atom.io/download/electron/v1.7.5/iojs-v1.7.5.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 52.216.64.216:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1050:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1073:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/opt/local/bin/node" "/Users/andrew/dev/st/desktop-gen-electron/src/app/node_modules/.bin/node-gyp" "rebuild" "--target=1.7.5" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /Users/andrew/dev/st/desktop-gen-electron/src/app/node_modules/sharp
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

That host maps to `s3-1-w.amazonaws.com`, and going to that url gives you the message that all access has been disabled.  After that I was able to complete the rebuild!

Anyway, try going to that url, maybe it'll help someone in the future.
