### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by aranea-networks** [JoelBesada/activate-power-mode#262]
Uncaught TypeError
![20170402-activate-power-mode-uncaughttypeerror](https://cloud.githubusercontent.com/assets/2781024/24589767/8790d89c-17e0-11e7-998f-a7dcb759a5e5.png)
: atom.views.getView(...).shadowRoot.elementFromPoint is not a function
C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:823
Show Stack Trace
The error was thrown from the activate-power-mode-delete package. You can help by creating an issue. Please explain what actions triggered this error.

**Comment by aranea-networks** [comment]
TypeError: atom.views.getView(...).shadowRoot.elementFromPoint is not a function
    at Object.getColorAtPosition (file:///C:/Users/os-admin/.atom/packages/activate-power-mode-delete/lib/activate-power-mode.coffee:115:49)
    at Object.spawnParticles (file:///C:/Users/os-admin/.atom/packages/activate-power-mode-delete/lib/activate-power-mode.coffee:107:14)
    at Object.debounced [as throttledSpawnParticles] (C:\Users\os-admin\.atom\packages\activate-power-mode-delete\node_modules\lodash.debounce\index.js:182:23)
    at Object.onChange (file:///C:/Users/os-admin/.atom/packages/activate-power-mode-delete/lib/activate-power-mode.coffee:76:10)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:679:20)
    at TextBuffer.module.exports.TextBuffer.applyChange (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:663:12)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:556:19)
    at TextBuffer.module.exports.TextBuffer.delete (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:686:19)
    at Selection.module.exports.Selection.deleteSelectedText (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\selection.js:586:37)
    at Selection.module.exports.Selection.backspace (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\selection.js:511:19)
    at C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\text-editor.js:1140:26
    at C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\text-editor.js:1156:28
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:818:18)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\text-editor.js:1589:26)
    at C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\text-editor.js:1150:24
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\text-editor.js:2567:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\text-editor.js:2529:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\text-editor.js:1148:19)
    at TextEditor.module.exports.TextEditor.backspace (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\text-editor.js:1139:19)
    at TextEditor.object.(anonymous function) [as backspace] (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:77:27)
    at TextEditor.core:backspace (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\register-default-commands.js:425:21)
    at C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\register-default-commands.js:666:34
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:818:18)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\text-editor.js:1589:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\register-default-commands.js:665:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\command-registry.js:259:29)
    at C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (C:\Users\os-admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\window-event-handler.js:3:59)

**Comment by lexcast** [comment]
Hi @aranea-networks 
The package you are using is a fork of this one.
https://github.com/valmassoi/activate-power-mode-delete
