### ISSUE TITLE
Failed to load the activate-power-mode package

### ISSUE THREAD

**Issue by ynyangjinlong** [JoelBesada/activate-power-mode#263]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package 1.4.0

### Stack Trace

Failed to load the activate-power-mode package

```
At Cannot find module 'lodash.throttle'

Error: Cannot find module 'lodash.throttle'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/activate-power-mode/lib/power-editor.coffee:1:12)
    at /packages/activate-power-mode/lib/power-editor.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/activate-power-mode/lib/activate-power-mode.coffee:4:15)
    at /packages/activate-power-mode/lib/activate-power-mode.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
citd-editor 0.1.0 
```

**Comment by lexcast** [comment]
Hi @ynyangjinlong 
How are you installing the package?

**Comment by lexcast** [comment]
Closing for lack of activity, Open again if the issue persist with the latest release.
