### ISSUE TITLE
Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by maninwindow** [JoelBesada/activate-power-mode#27]
I got this error when I activate this package on Windows atom. Have someone had this error?

TypeError: Cannot read property 'classList' of undefined
    at Object.module.exports.ActivatePowerMode.activate (file:///C:/Users/v-almett/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:20:19)
    at Package.module.exports.Package.activateNow (C:\Users\v-almett\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:170:19)
    at C:\Users\v-almett\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:738:25
    at Emitter.module.exports.Emitter.emit (C:\Users\v-almett\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\v-almett\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (C:\Users\v-almett\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\v-almett\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\v-almett\AppData\Local\atom\app-1.2.4\resources\app.asar\src\atom-environment.js:987:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)

**Comment by wangzilongx** [comment]
There I have the same question,can anybody help ,thanks!

**Comment by maninwindow** [comment]
@wangzilongx i have solved it by myself.

**Comment by maninwindow** [comment]
Install Atom->File->Settings->install  search for active-power-mode->install. Packages->Command Palette->Toggle ,select active-power-mode Toggle then create a new file to try again. If it doesn't work go to View->Reload then try again. This is how i solve this problem.

**Comment by wangzilongx** [comment]
@maninwindow  thank you so much for solved my problem!

**Comment by snailteen** [comment]
ok ，i have solve the problem too thanks

**Comment by rogerluo** [comment]
following @maninwindow 's guide can solve the issue
