### ISSUE TITLE
Uncaught Error: Cannot find module 'etch'

### ISSUE THREAD

**Issue by Jerajo** [JoelBesada/activate-power-mode#276]
I'm trying to Test the new update but I got this error. After installing  `atom-select-list`. I don't know if I am missing something to put it work. @lexcast. If you can help me to solve this issue. To start using the new api and services.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Windows 10
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package 1.4.0

### Stack Trace

Uncaught Error: Cannot find module 'etch'

```
At C:\Users\jesse\AppData\Local\atom\app-1.17.2\resources\app\static\<embedded>:1

Error: Cannot find module 'etch'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:66:1)
    at /packages/activate-power-mode/node_modules/atom-select-list/src/select-list-view.js:2:14)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.17.2/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:66:1)
    at /packages/activate-power-mode/lib/flow-list.coffee:1:18)
    at /packages/activate-power-mode/lib/flow-list.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.17.2/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:66:1)
    at Object.initList (/packages/activate-power-mode/lib/flow-registry.coffee:44:17)
    at Object.enable (/packages/activate-power-mode/lib/flow-registry.coffee:12:6)
    at Object.enable (/packages/activate-power-mode/lib/plugin-manager.coffee:69:19)
    at Object.enable (/packages/activate-power-mode/lib/power-editor.coffee:7:20)
    at Object.enable (/packages/activate-power-mode/lib/activate-power-mode.coffee:43:18)
    at Object.toggle (/packages/activate-power-mode/lib/activate-power-mode.coffee:39:38)
    at /packages/activate-power-mode/lib/activate-power-mode.coffee:28:10
```

### Commands

```
     -1:31.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

**Comment by lexcast** [comment]
Hi @Jerajo try installing with `apm install` in the project root. It will install all dependencies.

**Comment by Jerajo** [comment]
Thanks @lexcast. It works now.

**Comment by ctejeda86** [comment]
> Hi @Jerajo try installing with `apm install` in the project root. It will install all dependencies.

Hi!! I have the same problem, I am a begginer in Julia, ¿could you explain me please what do you mean to "project root"?  Thank you very much. Best regards.

**Comment by Jerajo** [comment]
@ctejeda86 if your are making an extension for activate-power-mode in your package root folder you need to run `apm install` in the console.

if your are just installing the package your can use the apm command `apm install activate-power-mode` Or Settings ➔ Packages ➔ Search for `activate-power-mode`
