### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash.debounce'

### ISSUE THREAD

**Issue by okayliao** [JoelBesada/activate-power-mode#279]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package 2.0.0

### Stack Trace

Uncaught Error: Cannot find module 'lodash.debounce'

```
At module.js:457

Error: Cannot find module 'lodash.debounce'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:66:1)
    at /packages/activate-power-mode/lib/combo-renderer.coffee:2:12)
    at /packages/activate-power-mode/lib/combo-renderer.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.17.2/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:66:1)
    at /packages/activate-power-mode/lib/plugin-manager.coffee:3:17)
    at /packages/activate-power-mode/lib/plugin-manager.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.17.2/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:66:1)
    at /packages/activate-power-mode/lib/activate-power-mode.coffee:18:24
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
```

**Comment by Jerajo** [comment]
@AnglovLee Did you install the package by the ATOM installer? This kind of problem is caused for an incorrect installation. You can find more info here #276.

Also you can install it using the [ATOM Package Manager](https://github.com/atom/apm).

```csl
apm install activate-power-mode
```
