### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash.defer'

### ISSUE THREAD

**Issue by ChangerLee** [JoelBesada/activate-power-mode#285]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package 2.1.0

### Stack Trace

Uncaught Error: Cannot find module 'lodash.defer'

```
At C:\Users\lenovo\AppData\Local\atom\app-1.18.0\resources\app\static\<embedded>:1

Error: Cannot find module 'lodash.defer'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/activate-power-mode-master/lib/combo-renderer.coffee:3:9)
    at /packages/activate-power-mode-master/lib/combo-renderer.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/activate-power-mode-master/lib/plugin-manager.coffee:3:17)
    at /packages/activate-power-mode-master/lib/plugin-manager.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/activate-power-mode-master/lib/activate-power-mode.coffee:18:24
```

### Commands

```
     -0:30.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
activate-power-mode 2.1.0 
activate-power-mode 2.1.0 
an-color-picker 1.0.2 
angularjs 0.4.0 
angularjs-snippets 0.10.18 
atom-beautify 0.29.17 
atom-css-comb 3.1.0 
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
atom-prettify 0.1.3 
simplified-chinese-menu 3.5.0 
atom-ternjs 0.18.2 
autocomplete-paths 1.0.5 
autoprefixer 3.6.1 
browser-plus undefined 
color-picker 2.2.5 
css-snippets 1.1.0 
csslint 1.1.5 
emmet 2.4.3 
file-icons 2.1.1 
git-plus 7.3.3 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
jshint 1.8.6 
language-javascript-jsx 0.3.7 
linter 1.11.23 
linter-php 1.3.2 
linter-tidy 2.3.1 
merge-conflicts 1.4.4 
minimap 4.26.8 
node_modules undefined 
node-debugger 1.10.1 
nodejs-snippets 2.0.2 
react 0.16.2 
react-snippets 0.7.2 
run-in-browser 0.1.3 
seti-ui 1.7.0 
ss4.0-2.5.1 undefined 
xml-formatter 0.10.0 
```

**Comment by Jerajo** [comment]
@ChangerLee Did you install the package by the ATOM installer? This hind of problem is caused for and incorrect installation. You can find more info here #276.
