### ISSUE TITLE
Uncaught TypeError: Cannot read property 'observe' of null

### ISSUE THREAD

**Issue by JakeTheDev** [JoelBesada/activate-power-mode#304]
This occurs after the errors in #303, upon clicking in any pane with editor items.

Reproduction:

1. Update power-mode plugin to latest
2. Update Atom to 1.19.2 from 1.19.1
3. Restart atom to use new atom
4. Click in any pane with a file in it.
5. Error occurs.

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Ubuntu 14.04.5
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package 2.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'observe' of null

```
At /my_home_dir/.atom/packages/activate-power-mode/lib/canvas-renderer.coffee:72

TypeError: Cannot read property 'observe' of null
    at Object.setupCanvas (/packages/activate-power-mode/lib/canvas-renderer.coffee:72:20)
    at Object.onChangePane (/packages/activate-power-mode/lib/plugin/power-canvas.coffee:19:13)
    at /packages/activate-power-mode/lib/plugin-manager.coffee:87:32
    at Object.onEnabled (/packages/activate-power-mode/lib/plugin-registry.coffee:64:19)
    at Object.runOnChangePane (/packages/activate-power-mode/lib/plugin-manager.coffee:86:21)
    at Object.setupPane (/packages/activate-power-mode/lib/power-editor.coffee:40:20)
    at /packages/activate-power-mode/lib/power-editor.coffee:9:8
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /usr/share/atom/resources/app/src/workspace.js:551:30
```

### Commands

```
     -2:33.9.0 intentions:highlight (input.hidden-input)
     -2:33.3.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.4.0 
ariake-dark-syntax 0.1.3 
atom-material-syntax 1.0.6 
autocomplete-python 1.10.2 
automate-power-mode 0.2.1 
busy-signal 1.4.3 
chary-tree-view 0.2.13 
double-tag 0.9.0 
git-time-machine 1.5.9 
gloom 0.6.4 
intentions 1.1.5 
language-puppet 0.23.0 
language-source-cfg 0.3.1 
linter 2.2.0 
linter-puppet-lint 0.8.2 
linter-ui-default 1.6.7 
material-monokai-syntax 1.0.1 
multirow-tabs 0.3.3 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
northem-dark-atom-syntax 2.1.0 
platformio-ide-terminal 2.5.5 
power-effects 0.3.0 
pretty-json 1.6.4 
tree-view-copy-relative-path 1.2.0 
vim-mode-plus 0.97.2 
```

**Comment by JakeTheDev** [comment]
This only occurs when automate-power-mode is enabled, so this isn't really your problem, but now this case is here in case it happens to others and they're looking for answers

**Comment by Davidepaalte** [comment]
It seems fixed with the new update.
