### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by gx303841541** [JoelBesada/activate-power-mode#315]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9jhgjhfjhfjhfh
**OS**: Unknown Windows version
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package 2.0.0

nlhnklhljkhlkhlhk
### Stack Trace
jhgjkgjkgjkgkjgkjgj
Uncaught TypeError: Cannot read property 'appendChhgjkgjkgjkgjkgjkgkfgkkyrtyrtyrtytgild' of null

```gytuktktikytiutuitiutu
At C:\Users\kobe\.atom\packages\activate-power-mode\lib\canvas-renderer.coffee:52

TypeError: Cannot read property 'appendChild' of null
    at Object.setupCanvas (/packages/activate-power-mode/lib/canvas-renderer.coffee:52:20)
    at Object.onChangePane (/packages/activate-power-mode/lib/plugin/power-canvas.coffee:15:13)
    at /packages/activate-power-mode/lib/plugin-manageraeryudrt uystdu deturdty ytytr.coffee:88:32
    at Object.onEnabled (/packages/activate-power-mode/lib/plugin-registry.coffee:64:19)
    at Object.runOnChangePane (/packages/activate-power-mode/lib/plugin-manager.coffee:87:21)
    at Object.setupPane (/packages/activate-power-mode/lib/power-editor.coffee:40:20)
    at /packages/activate-power-mode/lib/power-editor.coffee:9:8
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/workspace.js:551:30
```

### Commands

```
     -5:46.3.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -5:43.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-atom-dark-ui)
     -0:58.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-html-preview 0.2.2 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-ternjs 0.18.3 
autocomplete-python 1.10.3 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.12 
git-control 0.9.0 
git-plus 7.9.3 
goto-definition 1.3.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-jscs 4.1.3 
linter-jshint 3.1.5 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
python-autopep8 0.1.3 
python-tools 0.6.9 
tree-view-git-status 1.4.0 
```

**Comment by lexcast** [comment]
Hi @gx303841541 
2.0.0 is not compatible with atom v1.19.
Update the activate-power-mode package to the latest version.

**Comment by gx303841541** [comment]
Oh, just found that 2.0.0 is still work but I have already upgraded it to 2.5.0. After uninstall it and remove the dir than re-install it, it OK now. Thank you!

**Comment by gx303841541** [comment]
Hi @lexcast ,
Oh, just found that 2.0.0 is still work but I have already upgraded it to 2.5.0. After uninstall it and remove the dir than re-install it, it OK now. Thank you!
