### ISSUE TITLE
win10下atom无法获取用户输入，报错

### ISSUE THREAD

**Issue by dragonliuhu** [JoelBesada/activate-power-mode#325]
安装script-ruuner提示错误

Installing “script-runner@2.2.1” failed.Hide output…

> node-pty@0.7.3 install C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-117116-6132-q52262.g0bmfe0zfr\node_modules\script-runner\node_modules\node-pty
> node scripts/install.js

C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-117116-6132-q52262.g0bmfe0zfr\node_modules\script-runner\node_modules\node-pty>if not defined npm_config_node_gyp (node "C:\Users\Administrator\AppData\Local\atom\app-1.17.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Administrator\AppData\Local\atom\app-1.17.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-117116-6132-q52262.g0bmfe0zfr
`-- (empty)

gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\python.EXE" is v3.6.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\Administrator\AppData\Local\atom\app-1.17.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\Administrator\AppData\Local\atom\app-1.17.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.17.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.17.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-117116-6132-q52262.g0bmfe0zfr\node_modules\script-runner\node_modules\node-pty
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-117116-6132-q52262.g0bmfe0zfr\package.json'
npm WARN apm-install-dir-117116-6132-q52262.g0bmfe0zfr No description
npm WARN apm-install-dir-117116-6132-q52262.g0bmfe0zfr No repository field.
npm WARN apm-install-dir-117116-6132-q52262.g0bmfe0zfr No README data
npm WARN apm-install-dir-117116-6132-q52262.g0bmfe0zfr No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.17.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.17.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Administrator\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Administrator\\.atom\\.apmrc" "install" "C:\\Users\\Administrator\\AppData\\Local\\Temp\\d-117116-6132-9axaeu.rdpw1xlxr\\package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! node-pty@0.7.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.7.3 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Local\Temp\apm-install-dir-117116-6132-q52262.g0bmfe0zfr\npm-debug.log
npm ERR! code 1

**Comment by lexcast** [comment]
Hi @dragonliuhu  It doesn't seem a problem with this package, it says `script-runner`. 
Can you install other packages normally?
