### ISSUE TITLE
Uncaught TypeError: Cannot read property 'observe' of null

### ISSUE THREAD

**Issue by 110662** [JoelBesada/activate-power-mode#330]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: "CentOS Linux
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package 2.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'observe' of null

```
At /home/myhome/.atom/packages/activate-power-mode/lib/canvas-renderer.coffee:72

TypeError: Cannot read property 'observe' of null
    at Object.setupCanvas (/packages/activate-power-mode/lib/canvas-renderer.coffee:72:20)
    at Object.onChangePane (/packages/activate-power-mode/lib/plugin/power-canvas.coffee:19:13)
    at /packages/activate-power-mode/lib/plugin-manager.coffee:90:32
    at Object.onEnabled (/packages/activate-power-mode/lib/plugin-registry.coffee:92:19)
    at Object.runOnChangePane (/packages/activate-power-mode/lib/plugin-manager.coffee:89:21)
    at Object.setupPane (/packages/activate-power-mode/lib/power-editor.coffee:40:20)
    at /packages/activate-power-mode/lib/power-editor.coffee:9:8
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /usr/share/atom/resources/app/src/workspace.js:550:30
```

### Commands

```
     -0:35.1.0 core:backspace (input.hidden-input)
     -0:34.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.30.9 
markdown-mindmap 0.4.2 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
markdown-writer 2.7.3 
tool-bar 1.1.6 
vim-mode 0.66.0 
vim-mode-plus 1.28.0 
wordcount 2.10.4 
```

**Comment by taketakeyyy** [comment]
This error occurred when I double-cliked a file to open while Untoggle(Packages -> Activate Power Mode -> Toggle) or Disable(Packages -> Activate Power Mode -> Disable) state.

P.S.
Sorry. There seem to be some conditions which this error occurs. I'm using "symbols-tree-view" package and "Minimap" package. After I repeatedly untoggled and toggled these packages, then this error didn't occur.

**Comment by lkdvc** [comment]
1. Create new file
2. Have Git open (bottom right icon e.g. "4 files")

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: USER-PC
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package 2.7.0


### Stack Trace

Uncaught TypeError: Cannot read property 'observe' of null

```
At C:\Users\Jan Luca Krebs\.atom\packages\activate-power-mode\lib\canvas-renderer.coffee:72

TypeError: Cannot read property 'observe' of null
    at Object.setupCanvas (/packages/activate-power-mode/lib/canvas-renderer.coffee:72:21)
    at Object.onChangePane (/packages/activate-power-mode/lib/plugin/power-canvas.coffee:19:13)
    at /packages/activate-power-mode/lib/plugin-manager.coffee:90:32
    at Object.onEnabled (/packages/activate-power-mode/lib/plugin-registry.coffee:92:19)
    at Object.runOnChangePane (/packages/activate-power-mode/lib/plugin-manager.coffee:89:21)
    at Object.setupPane (/packages/activate-power-mode/lib/power-editor.coffee:40:20)
    at /packages/activate-power-mode/lib/power-editor.coffee:9:8
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at stoppedChangingActivePaneItemTimeout.setTimeout (~/AppData/Local/atom/app-1.29.0/resources/app/src/workspace.js:493:26)
```

### Commands

```
  2x -5:36.9.0 intentions:highlight (input.hidden-input)
     -5:35.4.0 command-palette:toggle (input.hidden-input)
     -5:28.9.0 core:confirm (input.hidden-input)
     -5:28.9.0 activate-power-mode:enable (input.hidden-input)
     -5:25.8.0 intentions:highlight (input.hidden-input)
     -5:25.6.0 command-palette:toggle (input.hidden-input)
     -5:23.9.0 core:confirm (input.hidden-input)
     -5:23.9.0 activate-power-mode:enable (input.hidden-input)
     -5:01.6.0 intentions:highlight (input.hidden-input)
     -5:01.2.0 command-palette:toggle (input.hidden-input)
     -4:59.2.0 core:confirm (input.hidden-input)
     -4:59.2.0 activate-power-mode:toggle (input.hidden-input)
     -1:42.3.0 platformio-ide-terminal:context-rename (i.icon.icon-terminal)
     -1:38.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.32.5 
atom-clock 0.1.16 
busy-signal 1.4.3 
color-picker 2.3.0 
file-icons 2.1.22 
highlight-selected 0.14.0 
Hydrogen 2.5.1 
intentions 1.1.5 
linter 2.2.0 
linter-csslint 2.0.1 
linter-htmlhint 1.4.0 
linter-jshint 3.1.8 
linter-php 1.5.1 
linter-sass-lint 1.8.3 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-selection 4.5.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.3 
sort-lines 0.18.0 
teletype 0.13.3 
```

**Comment by asdf23** [comment]
To trigger this bug turn off the feature.
