### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash.random'

### ISSUE THREAD

**Issue by tntim96** [JoelBesada/activate-power-mode#338]
Get this on startup.

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: LMDE 2
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package 2.7.0

### Stack Trace

Uncaught Error: Cannot find module 'lodash.random'

```
At module.js:545

Error: Cannot find module 'lodash.random'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/activate-power-mode/lib/effect/particles.coffee:1:10)
    at /packages/activate-power-mode/lib/effect/particles.coffee:1:1)
    at /packages/activate-power-mode/lib/effect/particles.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/activate-power-mode/lib/plugin-manager.coffee:2:19)
    at /packages/activate-power-mode/lib/plugin-manager.coffee:1:1)
    at /packages/activate-power-mode/lib/plugin-manager.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/activate-power-mode/lib/activate-power-mode.coffee:18:24
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-ide-ui 0.13.0 
atom-typescript 12.6.3 
es6-javascript 1.0.0 
hex 0.6.2 
ide-html 0.4.2 
language-babel 2.85.0 
```

**Comment by jacksama123** [comment]
+1

**Comment by wjdwithyou** [comment]
+1

**Comment by chaiXiaoDuo** [comment]
+1
