### ISSUE TITLE
This happens while installing any pakage:

### ISSUE THREAD

**Issue by Ali332** [JoelBesada/activate-power-mode#347]
C:\Users\Ali\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:144
        throw er
        ^

Error: EPERM: operation not permitted, read
    at Object.fs.readSync (fs.js:675:18)
    at Object.readSync (C:\Users\Ali\AppData\Local\atom\app-1.38.2\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:138:28)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:575:19)
    at Object.Module._extensions..js (module.js:645:20)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)

**Comment by Ali332** [comment]
Someone please help me
