### ISSUE TITLE
Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by Kevin762** [JoelBesada/activate-power-mode#37]
TypeError: Cannot read property 'classList' of undefined
    at Object.module.exports.ActivatePowerMode.activate (file:///C:/Users/Kevin/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:20:19)
    at Package.module.exports.Package.activateNow (C:\Users\Kevin\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:170:19)
    at C:\Users\Kevin\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:738:25
    at Emitter.module.exports.Emitter.emit (C:\Users\Kevin\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Kevin\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (C:\Users\Kevin\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Kevin\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Kevin\AppData\Local\atom\app-1.2.4\resources\app.asar\src\atom-environment.js:987:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)

**Comment by snailteen** [comment]
i ‘ve same question too

**Comment by mqiy** [comment]
so do I

**Comment by lexcast** [comment]
is this still happening with the latest version?

**Comment by lexcast** [comment]
Closing issues on old versions of this package.

Open again if the problem persists with the latest release.
