### ISSUE TITLE
window10 can't use

### ISSUE THREAD

**Issue by smallyard** [JoelBesada/activate-power-mode#46]
[Enter steps to reproduce below:]

1.setup and toggle

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: 'activate-power-mode-0.3.2' package, vundefined

### Stack Trace

Failed to activate the activate-power-mode package

```
At Cannot read property 'classList' of undefined

TypeError: Cannot read property 'classList' of undefined
    at Object.module.exports.ActivatePowerMode.activate (file:///C:/Users/lyc/.atom/packages/activate-power-mode-0.3.2/lib/activate-power-mode.coffee:20:19)
    at Package.module.exports.Package.activateNow (C:\Users\lyc\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:170:19)
    at C:\Users\lyc\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:738:25
    at Emitter.module.exports.Emitter.emit (C:\Users\lyc\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\lyc\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (C:\Users\lyc\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\lyc\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\lyc\AppData\Local\atom\app-1.2.4\resources\app.asar\src\atom-environment.js:987:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
  3x -2:49.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:48.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -2:47.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -2:27.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -2:25.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:54.8.0 activate-power-mode:toggle (div.panels)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.3.2

# Dev
No dev packages
```

**Comment by lexcast** [comment]
use the latest version to see if this is fixed

**Comment by lexcast** [comment]
Closing issues on old versions of this package.

Open again if the problem persists with the latest release.
