### ISSUE TITLE
Failed to activate the activate-power-mode package

### ISSUE THREAD

**Issue by pjshy** [JoelBesada/activate-power-mode#5]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.0-beta6
**System**: Unknown Windows Version
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.3.2

### Stack Trace

Failed to activate the activate-power-mode package

```
At Cannot find module 'lodash.throttle'

Error: Cannot find module 'lodash.throttle'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (F:\atom\Atom Beta\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (F:\atom\Atom Beta\resources\app.asar\src\native-compile-cache.js:41:21)
    at Object.<anonymous> (file:///C:/Users/peidepc/.atom/packages/activate-power-mode-master/lib/activate-power-mode.coffee:1:12)
    at Object.<anonymous> (file:///C:/Users/peidepc/.atom/packages/activate-power-mode-master/lib/activate-power-mode.coffee:1:1)
    at Module._compile (F:\atom\Atom Beta\resources\app.asar\src\native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (F:\atom\Atom Beta\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (F:\atom\Atom Beta\resources\app.asar\src\native-compile-cache.js:41:21)
    at Package.module.exports.Package.requireMainModule (F:\atom\Atom Beta\resources\app.asar\src\package.js:663:34)
    at Package.module.exports.Package.activateConfig (F:\atom\Atom Beta\resources\app.asar\src\package.js:188:14)
    at Package.module.exports.Package.activateNow (F:\atom\Atom Beta\resources\app.asar\src\package.js:166:14)
    at F:\atom\Atom Beta\resources\app.asar\src\package.js:740:25
    at Emitter.module.exports.Emitter.emit (F:\atom\Atom Beta\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (F:\atom\Atom Beta\resources\app.asar\src\command-registry.js:241:20)
    at F:\atom\Atom Beta\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (F:\atom\Atom Beta\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (F:\atom\Atom Beta\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (F:\atom\Atom Beta\resources\app.asar\src\window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (F:\atom\Atom Beta\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:11 activate-power-mode:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by geeeeeeeeek** [comment]
+1

**Comment by phyjs1018** [comment]
解压压缩包后，需要用npm安装相应的依赖模块

**Comment by yoyojacky** [comment]
npm 安装什么模块呢？ 
what  kind of modules need to be installed by npm ?

**Comment by sner1919** [comment]
没明白，什么是npm? 你们用的是什么系统？

**Comment by geeeeeeeeek** [comment]
没逗我吧..npm不知道么..node package manager啊
难道你atom不是npm装的么..

**Comment by sner1919** [comment]
要不要这么大惊小怪的。不是啊，我装在windows电脑上了，装atom的时候只是下载了一个安装包啊

**Comment by wy-ang** [comment]
完全不好使。

**Comment by wy-ang** [comment]
npm install easyimage也没用而且  atom特别的卡。还是sublimt吧。

**Comment by sner1919** [comment]
一直在用sublime， atom特别地占内存。看了朋友圈酷绚地图片才来下载的。

**Comment by Crazytinal** [comment]
I've found that if you wanna toggle activate-atom-mode package in “setting”, it fails...but if you toggle it in a new file(ctrl+n), it works....我在设定的界面直接启动这插件时，会报错，但是当我在新建一个文件后，在里面启动时，成功了，并不需要装其他插件

**Comment by geeeeeeeeek** [comment]
我在思考一个问题，为什么上面都是中国人..莫非你们也是看了微博来的？

**Comment by miyagiyu** [comment]
完全没看懂 到底要怎么解决

**Comment by YangNull** [comment]
尝试很多办法，还没解决

**Comment by miyagiyu** [comment]
我是直接在settings里面install package  然后done了之后 新建文件也要修改文件也好 都没有任何炫酷的事情发生。。

**Comment by sner1919** [comment]
你新建文件然后要激活这个package要按 ctrl+alt+O。

**Comment by trickysky** [comment]
进到package的目录，把源码放在该目录下，进去以后可以看见一个package.json的文件，命令行
nmp install 就OK了

**Comment by poboke** [comment]
npm install lodash.throttle

**Comment by BuptStEve** [comment]
赞同 @trickysky 
原因就是没有装依赖，
所以你使用命令行进入 atom 的 package 目录下的 activate-power-mode 目录执行
```bash
npm install
```
就 ok 了～=￣ω￣=～

**Comment by pkxpp** [comment]
* i use npm install is also error. gyp err.
* but i can see this package in packages->activate-power-mode. I start manauly, and give me tip this url.
* and then i restart atom, and excute "npm install", the result is success. And I see the it.

**Comment by Kevin762** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.3.2


### Stack Trace

Failed to activate the activate-power-mode package

```
At Cannot read property 'classList' of undefined

TypeError: Cannot read property 'classList' of undefined
    at Object.module.exports.ActivatePowerMode.activate (file:///C:/Users/Kevin/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:20:19)
    at Package.module.exports.Package.activateNow (C:\Users\Kevin\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:170:19)
    at C:\Users\Kevin\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:738:25
    at Emitter.module.exports.Emitter.emit (C:\Users\Kevin\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Kevin\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (C:\Users\Kevin\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Kevin\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Kevin\AppData\Local\atom\app-1.2.4\resources\app.asar\src\atom-environment.js:987:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:08.0 activate-power-mode:toggle (button.btn.icon.enablement.icon-playback-pause)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.3.2

# Dev
No dev packages
```

**Comment by Crazytinal** [comment]
@Kevin762  your situation is different....the error you meet is [here](https://github.com/JoelBesada/activate-power-mode/issues/27)

**Comment by hwmagical** [comment]
看来都是看了朋友圈来的 然后装了又用不了

**Comment by alexgleason** [comment]
Duplicate of #9. Run `npm install` in the project directory to install the package dependencies.

**Comment by lerryxiao** [comment]
Mac 上使用 apm install 安装成功了， 打开 atom ； 点击 Atom-》Install Shell Command;  在~/.atom/packages 目录下 git clone 代码，进入代码目录，atom install 即可

**Comment by lerryxiao** [comment]
有人在 Sublime text 2 安装了吗

**Comment by poboke** [comment]
高仿了个Xcode版的 [https://github.com/poboke/ActivatePowerMode](https://github.com/poboke/ActivatePowerMode)

**Comment by trickysky** [comment]
@poboke 体验了xcode版本，真是酷炫

**Comment by MwumLi** [comment]
1. 下载 nodejs,默认安装 : < https://nodejs.org/en/>
2.  打开 cmd:  
 
             cd .atom/packages
             npm install
    等待安装完成即可
3, 打开 atom, 按下 `ctrl-alt-o`  

4. 失效的情况下，重启 atom, `ctrl-alt-r`

**Comment by yanluckly** [comment]
Windows没有NPM命令怎么办啊

**Comment by trickysky** [comment]
@yanluckly 安装node.js环境就有npm了

**Comment by yanluckly** [comment]
@trickysky Thank You

**Comment by kinkin0007** [comment]
赞同 @trickysky  成功了！

**Comment by andy521** [comment]
good plugins

**Comment by lexcast** [comment]
install by running `apm install activate-power-mode`
