### ISSUE TITLE
Uncaught Error: Can't save buffer with no file path

### ISSUE THREAD

**Issue by kelvinlove** [JoelBesada/activate-power-mode#77]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.3.2

### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At E:\atom-windows\Atom\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1008

Error: Can't save buffer with no file path
    at TextBuffer.module.exports.TextBuffer.saveAs (E:\atom-windows\Atom\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1008:15)
    at TextBuffer.module.exports.TextBuffer.save (E:\atom-windows\Atom\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1002:19)
    at TextEditor.module.exports.TextEditor.save (E:\atom-windows\Atom\resources\app.asar\src\text-editor.js:557:26)
    at atom-text-editor.compile (C:\Users\Administrator\.atom\packages\gpp-compiler\index.js:32:12)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (E:\atom-windows\Atom\resources\app.asar\src\command-registry.js:260:29)
    at E:\atom-windows\Atom\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (E:\atom-windows\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (E:\atom-windows\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (E:\atom-windows\Atom\resources\app.asar\src\window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (E:\atom-windows\Atom\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
  3x -5:24.7.0 core:backspace (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
  2x -5:20.5.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
     -5:14.6.0 autocomplete-plus:confirm (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -5:14.6.0 snippets:expand (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -5:11.5.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -4:57.6.0 command-palette:toggle (atom-text-editor.editor.power-mode.is-focused)
  6x -4:51.2.0 gpp-compiler:compile (atom-text-editor.editor.power-mode)
     -4:23.3.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
  2x -4:16.8.0 gpp-compiler:compile (atom-text-editor.editor.power-mode.is-focused)
     -2:12.7.0 activate-power-mode:toggle (atom-text-editor.editor.power-mode.is-focused)
  2x -2:09.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -2:07.0 window:run-package-specs (atom-text-editor.editor.power-mode.is-focused)
     -2:03.9.0 application:open-folder (atom-text-editor.editor.power-mode.is-focused)
     -2:00.8.0 activate-power-mode:toggle (atom-text-editor.editor.power-mode.is-focused)
  3x -2:00.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
  8x -1:55.6.0 gpp-compiler:compile (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.3.2
gpp-compiler, v1.1.0

# Dev
No dev packages
```

**Comment by lexcast** [comment]
use the latest version to see if it is fixed

**Comment by lexcast** [comment]
Closing issues on old versions of this package.

Open again if the problem persists with the latest release.
