### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash.throttle'

### ISSUE THREAD

**Issue by lizilin1993** [JoelBesada/activate-power-mode#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.3.2

### Stack Trace

Uncaught Error: Cannot find module 'lodash.throttle'

```
At module.js:338

Error: Cannot find module 'lodash.throttle'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (D:\Atom\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (file:///C:/Users/lizilin/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:1:12)
    at Object.<anonymous> (file:///C:/Users/lizilin/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (D:\Atom\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (D:\Atom\resources\app.asar\src\package.js:661:34)
    at Package.module.exports.Package.activateConfig (D:\Atom\resources\app.asar\src\package.js:188:14)
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (D:\Atom\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:215:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (D:\Atom\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:158:12)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (D:\Atom\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:170:21)
    at PackageDetailView.module.exports.PackageDetailView.initialize (D:\Atom\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:145:19)
    at PackageDetailView.View [as constructor] (D:\Atom\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
    at PackageDetailView.ScrollView [as constructor] (D:\Atom\resources\app.asar\node_modules\atom-space-pen-views\lib\scroll-view.js:12:47)
    at new PackageDetailView (D:\Atom\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:38:54)
    at D:\Atom\resources\app.asar\node_modules\settings-view\lib\settings-view.js:269:22
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (D:\Atom\resources\app.asar\node_modules\settings-view\lib\settings-view.js:274:19)
    at SettingsView.module.exports.SettingsView.showPanel (D:\Atom\resources\app.asar\node_modules\settings-view\lib\settings-view.js:320:24)
    at space-pen-div.<anonymous> (D:\Atom\resources\app.asar\node_modules\settings-view\lib\package-card.js:262:83)
    at space-pen-div.jQuery.event.dispatch (D:\Atom\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at space-pen-div.elemData.handle (D:\Atom\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -3:29.4.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode",
      "activate-power-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by ScottKaye** [comment]
Run `npm install` in the base directory of activate-power-mode (`~\.atom\packages\activate-power-mode`) to download `lodash_throttle`.

You might also be able to run `npm install -g lodash_throttle`, but the procedure above is better.
