### ISSUE TITLE
Failed to activate the activate-power-mode package

### ISSUE THREAD

**Issue by liyeting** [JoelBesada/activate-power-mode#93]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Unknown Windows Version
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package, v0.4.1

### Stack Trace

Failed to activate the activate-power-mode package

```
At Cannot read property 'parentNode' of undefined

TypeError: Cannot read property 'parentNode' of undefined
    at Object.module.exports.ActivatePowerMode.setupCanvas (file:///C:/Users/liyeting/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:48:19)
    at Object.module.exports.ActivatePowerMode.activate (file:///C:/Users/liyeting/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:22:6)
    at Package.module.exports.Package.activateNow (C:\Users\liyeting\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:170:19)
    at C:\Users\liyeting\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:740:25
    at Emitter.module.exports.Emitter.emit (C:\Users\liyeting\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\liyeting\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:241:20)
    at C:\Users\liyeting\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\liyeting\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\liyeting\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\liyeting\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\liyeting\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
  2x -2:28.5.0 application:add-project-folder (atom-text-editor.editor.is-focused)
  2x -1:43.4.0 activate-power-mode:toggle (button.btn.icon.enablement.icon-playback-pause)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "openEmptyEditorOnStart": false
  },
  "activate-power-mode": {
    "particles": {
      "size": {},
      "spawnCount": {},
      "totalCount": {}
    },
    "screenShake": {}
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.4.1

# Dev
No dev packages
```

**Comment by jshamley** [comment]
I got the same error when trying to activate power mode. No special steps to reproduce. Also got this error https://github.com/JoelBesada/activate-power-mode/issues/81

Atom: v1.3.2
activate-power-mode: v0.4.1
System: Mac OSX Yosemite 10.10.5

**Comment by Shyam-Chen** [comment]
File > Settings > Install
Search activate-power-mode
Click Install
Alt + Ctrl + R > Alt + Ctrl +O

I have successfully used.

**Comment by jshamley** [comment]
Today the package is working for me with no errors.

**Comment by lexcast** [comment]
already fixed, use the latest version
